#!/bin/sh

# force sudo password entry early
sudo uptime

# clean build
echo "-- clean build folder\n"
rm -rf ~/OpenCOP-2.0/build/
mkdir ~/OpenCOP-2.0/build/

# build war
echo "-- build war\n"
cd ~/OpenCOP-2.0/web_app/
jar cvf ../build/opencop.war .
cd -

# delete existing war/folder in tomcat
echo "-- clean tomcat\n"
sudo rm -rf /var/lib/tomcat6/webapps/opencop/
sudo rm /var/lib/tomcat6/webapps/opencop.war

# copy new war to tomcat
echo "-- copy war to tomcat\n"
sudo cp ~/OpenCOP-2.0/build/opencop.war /var/lib/tomcat6/webapps

echo "==================="
echo "You, sir, are done!\n"
