#!/bin/sh

# clean opencop build
echo "-- clean build folder\n"
rm -rf ~/OpenCOP/build/
mkdir ~/OpenCOP/build/

# build opencop war
echo "-- build war\n"
cd ~/OpenCOP/web_app/
jar cvf ../build/opencop.war .
cd -

# copy new opencop war to tomcat
echo "-- copy war to tomcat\n"
cp ~/OpenCOP/build/opencop.war /var/lib/tomcat6/webapps

echo "==================="
echo "You, sir, are done!\n"
