#!/bin/sh

# build opencop war
echo "-- build war\n"
cd ~/OpenCOP/
mvn clean install

# copy new opencop war to tomcat
# Note:
#   For reasons passing understanding, this echo MUST be
#   commented out in order for this script to run
#   correctly in a cronjob on the server.
#echo "-- copy war to tomcat\n"
cp ~/OpenCOP/target/opencop.war /var/lib/tomcat6/webapps

echo "==================="
echo "You, sir, are done!\n"
