insert into icon (id, name, url) values (4001, 'Agri Agricultural Laboratories S1',	'http://localhost/opencop-icons/HSWG/Agri_Agricultural_Laboratories_S1.png');
insert into icon (id, name, url) values (4002, 'Agri Agricultural Laboratories S2',	'http://localhost/opencop-icons/HSWG/Agri_Agricultural_Laboratories_S2.png');
insert into icon (id, name, url) values (4003, 'Agri Agricultural Laboratories S3',	'http://localhost/opencop-icons/HSWG/Agri_Agricultural_Laboratories_S3.png');
insert into icon (id, name, url) values (4004, 'Agri Agricultural Laboratories S4',	'http://localhost/opencop-icons/HSWG/Agri_Agricultural_Laboratories_S4.png');
insert into icon (id, name, url) values (4005, 'Agri Animal Feedlots S1',	'http://localhost/opencop-icons/HSWG/Agri_Animal_Feedlots_S1.png');
insert into icon (id, name, url) values (4006, 'Agri Animal Feedlots S2',	'http://localhost/opencop-icons/HSWG/Agri_Animal_Feedlots_S2.png');
insert into icon (id, name, url) values (4007, 'Agri Animal Feedlots S3',	'http://localhost/opencop-icons/HSWG/Agri_Animal_Feedlots_S3.png');
insert into icon (id, name, url) values (4008, 'Agri Animal Feedlots S4',	'http://localhost/opencop-icons/HSWG/Agri_Animal_Feedlots_S4.png');
insert into icon (id, name, url) values (4009, 'Agri Commercial Food Distribution Center S1',	'http://localhost/opencop-icons/HSWG/Agri_Commercial_Food_Distribution_Center_S1.png');
insert into icon (id, name, url) values (4010, 'Agri Commercial Food Distribution Center S2',	'http://localhost/opencop-icons/HSWG/Agri_Commercial_Food_Distribution_Center_S2.png');
insert into icon (id, name, url) values (4011, 'Agri Commercial Food Distribution Center S3',	'http://localhost/opencop-icons/HSWG/Agri_Commercial_Food_Distribution_Center_S3.png');
insert into icon (id, name, url) values (4012, 'Agri Commercial Food Distribution Center S4',	'http://localhost/opencop-icons/HSWG/Agri_Commercial_Food_Distribution_Center_S4.png');
insert into icon (id, name, url) values (4013, 'Agriculture and Food Theme S1',	'http://localhost/opencop-icons/HSWG/Agriculture_and_Food_Theme_S1.png');
insert into icon (id, name, url) values (4014, 'Agriculture and Food Theme S2',	'http://localhost/opencop-icons/HSWG/Agriculture_and_Food_Theme_S2.png');
insert into icon (id, name, url) values (4015, 'Agriculture and Food Theme S3',	'http://localhost/opencop-icons/HSWG/Agriculture_and_Food_Theme_S3.png');
insert into icon (id, name, url) values (4016, 'Agriculture and Food Theme S4',	'http://localhost/opencop-icons/HSWG/Agriculture_and_Food_Theme_S4.png');
insert into icon (id, name, url) values (4017, 'Agri Farms Ranches S1',	'http://localhost/opencop-icons/HSWG/Agri_Farms_Ranches_S1.png');
insert into icon (id, name, url) values (4018, 'Agri Farms Ranches S2',	'http://localhost/opencop-icons/HSWG/Agri_Farms_Ranches_S2.png');
insert into icon (id, name, url) values (4019, 'Agri Farms Ranches S3',	'http://localhost/opencop-icons/HSWG/Agri_Farms_Ranches_S3.png');
insert into icon (id, name, url) values (4020, 'Agri Farms Ranches S4',	'http://localhost/opencop-icons/HSWG/Agri_Farms_Ranches_S4.png');
insert into icon (id, name, url) values (4021, 'Agri Food Production Center S1',	'http://localhost/opencop-icons/HSWG/Agri_Food_Production_Center_S1.png');
insert into icon (id, name, url) values (4022, 'Agri Food Production Center S2',	'http://localhost/opencop-icons/HSWG/Agri_Food_Production_Center_S2.png');
insert into icon (id, name, url) values (4023, 'Agri Food Production Center S3',	'http://localhost/opencop-icons/HSWG/Agri_Food_Production_Center_S3.png');
insert into icon (id, name, url) values (4024, 'Agri Food Production Center S4',	'http://localhost/opencop-icons/HSWG/Agri_Food_Production_Center_S4.png');
insert into icon (id, name, url) values (4025, 'Agri Food Retail S1',	'http://localhost/opencop-icons/HSWG/Agri_Food_Retail_S1.png');
insert into icon (id, name, url) values (4026, 'Agri Food Retail S2',	'http://localhost/opencop-icons/HSWG/Agri_Food_Retail_S2.png');
insert into icon (id, name, url) values (4027, 'Agri Food Retail S3',	'http://localhost/opencop-icons/HSWG/Agri_Food_Retail_S3.png');
insert into icon (id, name, url) values (4028, 'Agri Food Retail S4',	'http://localhost/opencop-icons/HSWG/Agri_Food_Retail_S4.png');
insert into icon (id, name, url) values (4029, 'Agri Grain Storage S1',	'http://localhost/opencop-icons/HSWG/Agri_Grain_Storage_S1.png');
insert into icon (id, name, url) values (4030, 'Agri Grain Storage S2',	'http://localhost/opencop-icons/HSWG/Agri_Grain_Storage_S2.png');
insert into icon (id, name, url) values (4031, 'Agri Grain Storage S3',	'http://localhost/opencop-icons/HSWG/Agri_Grain_Storage_S3.png');
insert into icon (id, name, url) values (4032, 'Agri Grain Storage S4',	'http://localhost/opencop-icons/HSWG/Agri_Grain_Storage_S4.png');
insert into icon (id, name, url) values (4033, 'Bank ATMs S1',	'http://localhost/opencop-icons/HSWG/Bank_ATMs_S1.png');
insert into icon (id, name, url) values (4034, 'Bank ATMs S2',	'http://localhost/opencop-icons/HSWG/Bank_ATMs_S2.png');
insert into icon (id, name, url) values (4035, 'Bank ATMs S3',	'http://localhost/opencop-icons/HSWG/Bank_ATMs_S3.png');
insert into icon (id, name, url) values (4036, 'Bank ATMs S4',	'http://localhost/opencop-icons/HSWG/Bank_ATMs_S4.png');
insert into icon (id, name, url) values (4037, 'Bank Banks S1',	'http://localhost/opencop-icons/HSWG/Bank_Banks_S1.png');
insert into icon (id, name, url) values (4038, 'Bank Banks S2',	'http://localhost/opencop-icons/HSWG/Bank_Banks_S2.png');
insert into icon (id, name, url) values (4039, 'Bank Banks S3',	'http://localhost/opencop-icons/HSWG/Bank_Banks_S3.png');
insert into icon (id, name, url) values (4040, 'Bank Banks S4',	'http://localhost/opencop-icons/HSWG/Bank_Banks_S4.png');
insert into icon (id, name, url) values (4041, 'Bank Bullion Storage S1',	'http://localhost/opencop-icons/HSWG/Bank_Bullion_Storage_S1.png');
insert into icon (id, name, url) values (4042, 'Bank Bullion Storage S2',	'http://localhost/opencop-icons/HSWG/Bank_Bullion_Storage_S2.png');
insert into icon (id, name, url) values (4043, 'Bank Bullion Storage S3',	'http://localhost/opencop-icons/HSWG/Bank_Bullion_Storage_S3.png');
insert into icon (id, name, url) values (4044, 'Bank Bullion Storage S4',	'http://localhost/opencop-icons/HSWG/Bank_Bullion_Storage_S4.png');
insert into icon (id, name, url) values (4045, 'Bank Federal Reserve Banks S1',	'http://localhost/opencop-icons/HSWG/Bank_Federal_Reserve_Banks_S1.png');
insert into icon (id, name, url) values (4046, 'Bank Federal Reserve Banks S2',	'http://localhost/opencop-icons/HSWG/Bank_Federal_Reserve_Banks_S2.png');
insert into icon (id, name, url) values (4047, 'Bank Federal Reserve Banks S3',	'http://localhost/opencop-icons/HSWG/Bank_Federal_Reserve_Banks_S3.png');
insert into icon (id, name, url) values (4048, 'Bank Federal Reserve Banks S4',	'http://localhost/opencop-icons/HSWG/Bank_Federal_Reserve_Banks_S4.png');
insert into icon (id, name, url) values (4049, 'Bank Financial Exchanges S1',	'http://localhost/opencop-icons/HSWG/Bank_Financial_Exchanges_S1.png');
insert into icon (id, name, url) values (4050, 'Bank Financial Exchanges S2',	'http://localhost/opencop-icons/HSWG/Bank_Financial_Exchanges_S2.png');
insert into icon (id, name, url) values (4051, 'Bank Financial Exchanges S3',	'http://localhost/opencop-icons/HSWG/Bank_Financial_Exchanges_S3.png');
insert into icon (id, name, url) values (4052, 'Bank Financial Exchanges S4',	'http://localhost/opencop-icons/HSWG/Bank_Financial_Exchanges_S4.png');
insert into icon (id, name, url) values (4053, 'Bank Financial Services Other S1',	'http://localhost/opencop-icons/HSWG/Bank_Financial_Services_Other_S1.png');
insert into icon (id, name, url) values (4054, 'Bank Financial Services Other S2',	'http://localhost/opencop-icons/HSWG/Bank_Financial_Services_Other_S2.png');
insert into icon (id, name, url) values (4055, 'Bank Financial Services Other S3',	'http://localhost/opencop-icons/HSWG/Bank_Financial_Services_Other_S3.png');
insert into icon (id, name, url) values (4056, 'Bank Financial Services Other S4',	'http://localhost/opencop-icons/HSWG/Bank_Financial_Services_Other_S4.png');
insert into icon (id, name, url) values (4057, 'Banking Finance Insurance Theme S1',	'http://localhost/opencop-icons/HSWG/Banking_Finance_Insurance_Theme_S1.png');
insert into icon (id, name, url) values (4058, 'Banking Finance Insurance Theme S2',	'http://localhost/opencop-icons/HSWG/Banking_Finance_Insurance_Theme_S2.png');
insert into icon (id, name, url) values (4059, 'Banking Finance Insurance Theme S3',	'http://localhost/opencop-icons/HSWG/Banking_Finance_Insurance_Theme_S3.png');
insert into icon (id, name, url) values (4060, 'Banking Finance Insurance Theme S4',	'http://localhost/opencop-icons/HSWG/Banking_Finance_Insurance_Theme_S4.png');
insert into icon (id, name, url) values (4061, 'Blank Emergency Operation A S1',	'http://localhost/opencop-icons/HSWG/Blank_Emergency_Operation_A_S1.png');
insert into icon (id, name, url) values (4062, 'Blank Emergency Operation A S2',	'http://localhost/opencop-icons/HSWG/Blank_Emergency_Operation_A_S2.png');
insert into icon (id, name, url) values (4063, 'Blank Emergency Operation A S3',	'http://localhost/opencop-icons/HSWG/Blank_Emergency_Operation_A_S3.png');
insert into icon (id, name, url) values (4064, 'Blank Emergency Operation A S4',	'http://localhost/opencop-icons/HSWG/Blank_Emergency_Operation_A_S4.png');
insert into icon (id, name, url) values (4065, 'Blank Emergency Operation B S1',	'http://localhost/opencop-icons/HSWG/Blank_Emergency_Operation_B_S1.png');
insert into icon (id, name, url) values (4066, 'Blank Emergency Operation B S2',	'http://localhost/opencop-icons/HSWG/Blank_Emergency_Operation_B_S2.png');
insert into icon (id, name, url) values (4067, 'Blank Emergency Operation B S3',	'http://localhost/opencop-icons/HSWG/Blank_Emergency_Operation_B_S3.png');
insert into icon (id, name, url) values (4068, 'Blank Emergency Operation B S4',	'http://localhost/opencop-icons/HSWG/Blank_Emergency_Operation_B_S4.png');
insert into icon (id, name, url) values (4069, 'Blank Incident A',	'http://localhost/opencop-icons/HSWG/Blank_Incident_A.png');
insert into icon (id, name, url) values (4070, 'Blank Incident B',	'http://localhost/opencop-icons/HSWG/Blank_Incident_B.png');
insert into icon (id, name, url) values (4071, 'Blank Infrastructure A S1',	'http://localhost/opencop-icons/HSWG/Blank_Infrastructure_A_S1.png');
insert into icon (id, name, url) values (4072, 'Blank Infrastructure A S2',	'http://localhost/opencop-icons/HSWG/Blank_Infrastructure_A_S2.png');
insert into icon (id, name, url) values (4073, 'Blank Infrastructure A S3',	'http://localhost/opencop-icons/HSWG/Blank_Infrastructure_A_S3.png');
insert into icon (id, name, url) values (4074, 'Blank Infrastructure A S4',	'http://localhost/opencop-icons/HSWG/Blank_Infrastructure_A_S4.png');
insert into icon (id, name, url) values (4075, 'Blank Infrastructure B S1',	'http://localhost/opencop-icons/HSWG/Blank_Infrastructure_B_S1.png');
insert into icon (id, name, url) values (4076, 'Blank Infrastructure B S2',	'http://localhost/opencop-icons/HSWG/Blank_Infrastructure_B_S2.png');
insert into icon (id, name, url) values (4077, 'Blank Infrastructure B S3',	'http://localhost/opencop-icons/HSWG/Blank_Infrastructure_B_S3.png');
insert into icon (id, name, url) values (4078, 'Blank Infrastructure B S4',	'http://localhost/opencop-icons/HSWG/Blank_Infrastructure_B_S4.png');
insert into icon (id, name, url) values (4079, 'Blank Natural Event A',	'http://localhost/opencop-icons/HSWG/Blank_Natural_Event_A.png');
insert into icon (id, name, url) values (4080, 'Blank Natural Event B',	'http://localhost/opencop-icons/HSWG/Blank_Natural_Event_B.png');
insert into icon (id, name, url) values (4081, 'Civil Demonstrations ch',	'http://localhost/opencop-icons/HSWG/Civil_Demonstrations_ch.png');
insert into icon (id, name, url) values (4082, 'Civil Demonstrations',	'http://localhost/opencop-icons/HSWG/Civil_Demonstrations.png');
insert into icon (id, name, url) values (4083, 'Civil Displaced Population ch',	'http://localhost/opencop-icons/HSWG/Civil_Displaced_Population_ch.png');
insert into icon (id, name, url) values (4084, 'Civil Displaced Population',	'http://localhost/opencop-icons/HSWG/Civil_Displaced_Population.png');
insert into icon (id, name, url) values (4085, 'Civil Disturbance Theme ch',	'http://localhost/opencop-icons/HSWG/Civil_Disturbance_Theme_ch.png');
insert into icon (id, name, url) values (4086, 'Civil Disturbance Theme',	'http://localhost/opencop-icons/HSWG/Civil_Disturbance_Theme.png');
insert into icon (id, name, url) values (4087, 'Civil Rioting ch',	'http://localhost/opencop-icons/HSWG/Civil_Rioting_ch.png');
insert into icon (id, name, url) values (4088, 'Civil Rioting',	'http://localhost/opencop-icons/HSWG/Civil_Rioting.png');
insert into icon (id, name, url) values (4089, 'Commercial Chemical Plant S1',	'http://localhost/opencop-icons/HSWG/Commercial_Chemical_Plant_S1.png');
insert into icon (id, name, url) values (4090, 'Commercial Chemical Plant S2',	'http://localhost/opencop-icons/HSWG/Commercial_Chemical_Plant_S2.png');
insert into icon (id, name, url) values (4091, 'Commercial Chemical Plant S3',	'http://localhost/opencop-icons/HSWG/Commercial_Chemical_Plant_S3.png');
insert into icon (id, name, url) values (4092, 'Commercial Chemical Plant S4',	'http://localhost/opencop-icons/HSWG/Commercial_Chemical_Plant_S4.png');
insert into icon (id, name, url) values (4093, 'Commercial Firearm Manufacturers S1',	'http://localhost/opencop-icons/HSWG/Commercial_Firearm_Manufacturers_S1.png');
insert into icon (id, name, url) values (4094, 'Commercial Firearm Manufacturers S2',	'http://localhost/opencop-icons/HSWG/Commercial_Firearm_Manufacturers_S2.png');
insert into icon (id, name, url) values (4095, 'Commercial Firearm Manufacturers S3',	'http://localhost/opencop-icons/HSWG/Commercial_Firearm_Manufacturers_S3.png');
insert into icon (id, name, url) values (4096, 'Commercial Firearm Manufacturers S4',	'http://localhost/opencop-icons/HSWG/Commercial_Firearm_Manufacturers_S4.png');
insert into icon (id, name, url) values (4097, 'Commercial Firearm Retailers S1',	'http://localhost/opencop-icons/HSWG/Commercial_Firearm_Retailers_S1.png');
insert into icon (id, name, url) values (4098, 'Commercial Firearm Retailers S2',	'http://localhost/opencop-icons/HSWG/Commercial_Firearm_Retailers_S2.png');
insert into icon (id, name, url) values (4099, 'Commercial Firearm Retailers S3',	'http://localhost/opencop-icons/HSWG/Commercial_Firearm_Retailers_S3.png');
insert into icon (id, name, url) values (4100, 'Commercial Firearm Retailers S4',	'http://localhost/opencop-icons/HSWG/Commercial_Firearm_Retailers_S4.png');
insert into icon (id, name, url) values (4101, 'Commercial Hazardous Material Production S1',	'http://localhost/opencop-icons/HSWG/Commercial_Hazardous_Material_Production_S1.png');
insert into icon (id, name, url) values (4102, 'Commercial Hazardous Material Production S2',	'http://localhost/opencop-icons/HSWG/Commercial_Hazardous_Material_Production_S2.png');
insert into icon (id, name, url) values (4103, 'Commercial Hazardous Material Production S3',	'http://localhost/opencop-icons/HSWG/Commercial_Hazardous_Material_Production_S3.png');
insert into icon (id, name, url) values (4104, 'Commercial Hazardous Material Production S4',	'http://localhost/opencop-icons/HSWG/Commercial_Hazardous_Material_Production_S4.png');
insert into icon (id, name, url) values (4105, 'Commercial Hazardous Material Storage S1',	'http://localhost/opencop-icons/HSWG/Commercial_Hazardous_Material_Storage_S1.png');
insert into icon (id, name, url) values (4106, 'Commercial Hazardous Material Storage S2',	'http://localhost/opencop-icons/HSWG/Commercial_Hazardous_Material_Storage_S2.png');
insert into icon (id, name, url) values (4107, 'Commercial Hazardous Material Storage S3',	'http://localhost/opencop-icons/HSWG/Commercial_Hazardous_Material_Storage_S3.png');
insert into icon (id, name, url) values (4108, 'Commercial Hazardous Material Storage S4',	'http://localhost/opencop-icons/HSWG/Commercial_Hazardous_Material_Storage_S4.png');
insert into icon (id, name, url) values (4109, 'Commercial Industrial Site S1',	'http://localhost/opencop-icons/HSWG/Commercial_Industrial_Site_S1.png');
insert into icon (id, name, url) values (4110, 'Commercial Industrial Site S2',	'http://localhost/opencop-icons/HSWG/Commercial_Industrial_Site_S2.png');
insert into icon (id, name, url) values (4111, 'Commercial Industrial Site S3',	'http://localhost/opencop-icons/HSWG/Commercial_Industrial_Site_S3.png');
insert into icon (id, name, url) values (4112, 'Commercial Industrial Site S4',	'http://localhost/opencop-icons/HSWG/Commercial_Industrial_Site_S4.png');
insert into icon (id, name, url) values (4113, 'Commercial Infrastructure Theme S1',	'http://localhost/opencop-icons/HSWG/Commercial_Infrastructure_Theme_S1.png');
insert into icon (id, name, url) values (4114, 'Commercial Infrastructure Theme S2',	'http://localhost/opencop-icons/HSWG/Commercial_Infrastructure_Theme_S2.png');
insert into icon (id, name, url) values (4115, 'Commercial Infrastructure Theme S3',	'http://localhost/opencop-icons/HSWG/Commercial_Infrastructure_Theme_S3.png');
insert into icon (id, name, url) values (4116, 'Commercial Infrastructure Theme S4',	'http://localhost/opencop-icons/HSWG/Commercial_Infrastructure_Theme_S4.png');
insert into icon (id, name, url) values (4117, 'Commercial Landfill S1',	'http://localhost/opencop-icons/HSWG/Commercial_Landfill_S1.png');
insert into icon (id, name, url) values (4118, 'Commercial Landfill S2',	'http://localhost/opencop-icons/HSWG/Commercial_Landfill_S2.png');
insert into icon (id, name, url) values (4119, 'Commercial Landfill S3',	'http://localhost/opencop-icons/HSWG/Commercial_Landfill_S3.png');
insert into icon (id, name, url) values (4120, 'Commercial Landfill S4',	'http://localhost/opencop-icons/HSWG/Commercial_Landfill_S4.png');
insert into icon (id, name, url) values (4121, 'Commercial Pharmaceutical Manufacturer S1',	'http://localhost/opencop-icons/HSWG/Commercial_Pharmaceutical_Manufacturer_S1.png');
insert into icon (id, name, url) values (4122, 'Commercial Pharmaceutical Manufacturer S2',	'http://localhost/opencop-icons/HSWG/Commercial_Pharmaceutical_Manufacturer_S2.png');
insert into icon (id, name, url) values (4123, 'Commercial Pharmaceutical Manufacturer S3',	'http://localhost/opencop-icons/HSWG/Commercial_Pharmaceutical_Manufacturer_S3.png');
insert into icon (id, name, url) values (4124, 'Commercial Pharmaceutical Manufacturer S4',	'http://localhost/opencop-icons/HSWG/Commercial_Pharmaceutical_Manufacturer_S4.png');
insert into icon (id, name, url) values (4125, 'Commercial Superfund Sites NPL S1',	'http://localhost/opencop-icons/HSWG/Commercial_Superfund_Sites_NPL_S1.png');
insert into icon (id, name, url) values (4126, 'Commercial Superfund Sites NPL S2',	'http://localhost/opencop-icons/HSWG/Commercial_Superfund_Sites_NPL_S2.png');
insert into icon (id, name, url) values (4127, 'Commercial Superfund Sites NPL S3',	'http://localhost/opencop-icons/HSWG/Commercial_Superfund_Sites_NPL_S3.png');
insert into icon (id, name, url) values (4128, 'Commercial Superfund Sites NPL S4',	'http://localhost/opencop-icons/HSWG/Commercial_Superfund_Sites_NPL_S4.png');
insert into icon (id, name, url) values (4129, 'Commercial Toxic Release Inventory S1',	'http://localhost/opencop-icons/HSWG/Commercial_Toxic_Release_Inventory_S1.png');
insert into icon (id, name, url) values (4130, 'Commercial Toxic Release Inventory S2',	'http://localhost/opencop-icons/HSWG/Commercial_Toxic_Release_Inventory_S2.png');
insert into icon (id, name, url) values (4131, 'Commercial Toxic Release Inventory S3',	'http://localhost/opencop-icons/HSWG/Commercial_Toxic_Release_Inventory_S3.png');
insert into icon (id, name, url) values (4132, 'Commercial Toxic Release Inventory S4',	'http://localhost/opencop-icons/HSWG/Commercial_Toxic_Release_Inventory_S4.png');
insert into icon (id, name, url) values (4133, 'Crime Bomb ch',	'http://localhost/opencop-icons/HSWG/Crime_Bomb_ch.png');
insert into icon (id, name, url) values (4134, 'Crime Bomb Explosion ch',	'http://localhost/opencop-icons/HSWG/Crime_Bomb_Explosion_ch.png');
insert into icon (id, name, url) values (4135, 'Crime Bomb Explosion',	'http://localhost/opencop-icons/HSWG/Crime_Bomb_Explosion.png');
insert into icon (id, name, url) values (4136, 'Crime Bomb',	'http://localhost/opencop-icons/HSWG/Crime_Bomb.png');
insert into icon (id, name, url) values (4137, 'Crime Bomb Threat ch',	'http://localhost/opencop-icons/HSWG/Crime_Bomb_Threat_ch.png');
insert into icon (id, name, url) values (4138, 'Crime Bomb Threat',	'http://localhost/opencop-icons/HSWG/Crime_Bomb_Threat.png');
insert into icon (id, name, url) values (4139, 'Crime Looting',	'http://localhost/opencop-icons/HSWG/Crime_Looting.png');
insert into icon (id, name, url) values (4140, 'Crime Poisoning',	'http://localhost/opencop-icons/HSWG/Crime_Poisoning.png');
insert into icon (id, name, url) values (4141, 'Crime Shooting',	'http://localhost/opencop-icons/HSWG/Crime_Shooting.png');
insert into icon (id, name, url) values (4142, 'Criminal Activity Theme ch',	'http://localhost/opencop-icons/HSWG/Criminal_Activity_Theme_ch.png');
insert into icon (id, name, url) values (4143, 'dotexample01',	'http://localhost/opencop-icons/HSWG/dotexample01.png');
insert into icon (id, name, url) values (4144, 'Educational Facilities Theme S1',	'http://localhost/opencop-icons/HSWG/Educational_Facilities_Theme_S1.png');
insert into icon (id, name, url) values (4145, 'Educational Facilities Theme S2',	'http://localhost/opencop-icons/HSWG/Educational_Facilities_Theme_S2.png');
insert into icon (id, name, url) values (4146, 'Educational Facilities Theme S3',	'http://localhost/opencop-icons/HSWG/Educational_Facilities_Theme_S3.png');
insert into icon (id, name, url) values (4147, 'Educational Facilities Theme S4',	'http://localhost/opencop-icons/HSWG/Educational_Facilities_Theme_S4.png');
insert into icon (id, name, url) values (4148, 'Edu College University S1',	'http://localhost/opencop-icons/HSWG/Edu_College_University_S1.png');
insert into icon (id, name, url) values (4149, 'Edu College University S2',	'http://localhost/opencop-icons/HSWG/Edu_College_University_S2.png');
insert into icon (id, name, url) values (4150, 'Edu College University S3',	'http://localhost/opencop-icons/HSWG/Edu_College_University_S3.png');
insert into icon (id, name, url) values (4151, 'Edu College University S4',	'http://localhost/opencop-icons/HSWG/Edu_College_University_S4.png');
insert into icon (id, name, url) values (4152, 'Edu Schools S1',	'http://localhost/opencop-icons/HSWG/Edu_Schools_S1.png');
insert into icon (id, name, url) values (4153, 'Edu Schools S2',	'http://localhost/opencop-icons/HSWG/Edu_Schools_S2.png');
insert into icon (id, name, url) values (4154, 'Edu Schools S3',	'http://localhost/opencop-icons/HSWG/Edu_Schools_S3.png');
insert into icon (id, name, url) values (4155, 'Edu Schools S4',	'http://localhost/opencop-icons/HSWG/Edu_Schools_S4.png');
insert into icon (id, name, url) values (4156, 'E Med Ambulance S1 ch',	'http://localhost/opencop-icons/HSWG/E_Med_Ambulance_S1_ch.png');
insert into icon (id, name, url) values (4157, 'E Med Ambulance S2 ch',	'http://localhost/opencop-icons/HSWG/E_Med_Ambulance_S2_ch.png');
insert into icon (id, name, url) values (4158, 'E Med Ambulance S3 ch',	'http://localhost/opencop-icons/HSWG/E_Med_Ambulance_S3_ch.png');
insert into icon (id, name, url) values (4159, 'E Med Ambulance S4 ch',	'http://localhost/opencop-icons/HSWG/E_Med_Ambulance_S4_ch.png');
insert into icon (id, name, url) values (4160, 'E Med Emergency Medical Theme S1',	'http://localhost/opencop-icons/HSWG/E_Med_Emergency_Medical_Theme_S1.png');
insert into icon (id, name, url) values (4161, 'E Med Emergency Medical Theme S2',	'http://localhost/opencop-icons/HSWG/E_Med_Emergency_Medical_Theme_S2.png');
insert into icon (id, name, url) values (4162, 'E Med Emergency Medical Theme S3',	'http://localhost/opencop-icons/HSWG/E_Med_Emergency_Medical_Theme_S3.png');
insert into icon (id, name, url) values (4163, 'E Med Emergency Medical Theme S4',	'http://localhost/opencop-icons/HSWG/E_Med_Emergency_Medical_Theme_S4.png');
insert into icon (id, name, url) values (4164, 'E Med EMT Station Locations S1',	'http://localhost/opencop-icons/HSWG/E_Med_EMT_Station_Locations_S1.png');
insert into icon (id, name, url) values (4165, 'E Med EMT Station Locations S2',	'http://localhost/opencop-icons/HSWG/E_Med_EMT_Station_Locations_S2.png');
insert into icon (id, name, url) values (4166, 'E Med EMT Station Locations S3',	'http://localhost/opencop-icons/HSWG/E_Med_EMT_Station_Locations_S3.png');
insert into icon (id, name, url) values (4167, 'E Med EMT Station Locations S4',	'http://localhost/opencop-icons/HSWG/E_Med_EMT_Station_Locations_S4.png');
insert into icon (id, name, url) values (4168, 'E Med Evacuation Helicopter Station S1',	'http://localhost/opencop-icons/HSWG/E_Med_Evacuation_Helicopter_Station_S1.png');
insert into icon (id, name, url) values (4169, 'E Med Evacuation Helicopter Station S2',	'http://localhost/opencop-icons/HSWG/E_Med_Evacuation_Helicopter_Station_S2.png');
insert into icon (id, name, url) values (4170, 'E Med Evacuation Helicopter Station S3',	'http://localhost/opencop-icons/HSWG/E_Med_Evacuation_Helicopter_Station_S3.png');
insert into icon (id, name, url) values (4171, 'E Med Evacuation Helicopter Station S4',	'http://localhost/opencop-icons/HSWG/E_Med_Evacuation_Helicopter_Station_S4.png');
insert into icon (id, name, url) values (4172, 'E Med Health Department Facility S1',	'http://localhost/opencop-icons/HSWG/E_Med_Health_Department_Facility_S1.png');
insert into icon (id, name, url) values (4173, 'E Med Health Department Facility S2',	'http://localhost/opencop-icons/HSWG/E_Med_Health_Department_Facility_S2.png');
insert into icon (id, name, url) values (4174, 'E Med Health Department Facility S3',	'http://localhost/opencop-icons/HSWG/E_Med_Health_Department_Facility_S3.png');
insert into icon (id, name, url) values (4175, 'E Med Health Department Facility S4',	'http://localhost/opencop-icons/HSWG/E_Med_Health_Department_Facility_S4.png');
insert into icon (id, name, url) values (4176, 'E Med Hospital S1',	'http://localhost/opencop-icons/HSWG/E_Med_Hospital_S1.png');
insert into icon (id, name, url) values (4177, 'E Med Hospital S2',	'http://localhost/opencop-icons/HSWG/E_Med_Hospital_S2.png');
insert into icon (id, name, url) values (4178, 'E Med Hospital S3',	'http://localhost/opencop-icons/HSWG/E_Med_Hospital_S3.png');
insert into icon (id, name, url) values (4179, 'E Med Hospital S4',	'http://localhost/opencop-icons/HSWG/E_Med_Hospital_S4.png');
insert into icon (id, name, url) values (4180, 'E Med Hospital Ship S1',	'http://localhost/opencop-icons/HSWG/E_Med_Hospital_Ship_S1.png');
insert into icon (id, name, url) values (4181, 'E Med Hospital Ship S2',	'http://localhost/opencop-icons/HSWG/E_Med_Hospital_Ship_S2.png');
insert into icon (id, name, url) values (4182, 'E Med Hospital Ship S3',	'http://localhost/opencop-icons/HSWG/E_Med_Hospital_Ship_S3.png');
insert into icon (id, name, url) values (4183, 'E Med Hospital Ship S4',	'http://localhost/opencop-icons/HSWG/E_Med_Hospital_Ship_S4.png');
insert into icon (id, name, url) values (4184, 'E Med Medical Facilities Out Patient S1',	'http://localhost/opencop-icons/HSWG/E_Med_Medical_Facilities_Out_Patient_S1.png');
insert into icon (id, name, url) values (4185, 'E Med Medical Facilities Out Patient S2',	'http://localhost/opencop-icons/HSWG/E_Med_Medical_Facilities_Out_Patient_S2.png');
insert into icon (id, name, url) values (4186, 'E Med Medical Facilities Out Patient S3',	'http://localhost/opencop-icons/HSWG/E_Med_Medical_Facilities_Out_Patient_S3.png');
insert into icon (id, name, url) values (4187, 'E Med Medical Facilities Out Patient S4',	'http://localhost/opencop-icons/HSWG/E_Med_Medical_Facilities_Out_Patient_S4.png');
insert into icon (id, name, url) values (4188, 'E Med Morgue S1',	'http://localhost/opencop-icons/HSWG/E_Med_Morgue_S1.png');
insert into icon (id, name, url) values (4189, 'E Med Morgue S2',	'http://localhost/opencop-icons/HSWG/E_Med_Morgue_S2.png');
insert into icon (id, name, url) values (4190, 'E Med Morgue S3',	'http://localhost/opencop-icons/HSWG/E_Med_Morgue_S3.png');
insert into icon (id, name, url) values (4191, 'E Med Morgue S4',	'http://localhost/opencop-icons/HSWG/E_Med_Morgue_S4.png');
insert into icon (id, name, url) values (4192, 'E Med Pharmacies S1',	'http://localhost/opencop-icons/HSWG/E_Med_Pharmacies_S1.png');
insert into icon (id, name, url) values (4193, 'E Med Pharmacies S2',	'http://localhost/opencop-icons/HSWG/E_Med_Pharmacies_S2.png');
insert into icon (id, name, url) values (4194, 'E Med Pharmacies S3',	'http://localhost/opencop-icons/HSWG/E_Med_Pharmacies_S3.png');
insert into icon (id, name, url) values (4195, 'E Med Pharmacies S4',	'http://localhost/opencop-icons/HSWG/E_Med_Pharmacies_S4.png');
insert into icon (id, name, url) values (4196, 'E Med Triage S1',	'http://localhost/opencop-icons/HSWG/E_Med_Triage_S1.png');
insert into icon (id, name, url) values (4197, 'E Med Triage S2',	'http://localhost/opencop-icons/HSWG/E_Med_Triage_S2.png');
insert into icon (id, name, url) values (4198, 'E Med Triage S3',	'http://localhost/opencop-icons/HSWG/E_Med_Triage_S3.png');
insert into icon (id, name, url) values (4199, 'E Med Triage S4',	'http://localhost/opencop-icons/HSWG/E_Med_Triage_S4.png');
insert into icon (id, name, url) values (4200, 'Emergency Collection Evacuation Point S1 ch',	'http://localhost/opencop-icons/HSWG/Emergency_Collection_Evacuation_Point_S1_ch.png');
insert into icon (id, name, url) values (4201, 'Emergency Collection Evacuation Point S1',	'http://localhost/opencop-icons/HSWG/Emergency_Collection_Evacuation_Point_S1.png');
insert into icon (id, name, url) values (4202, 'Emergency Collection Evacuation Point S2 ch',	'http://localhost/opencop-icons/HSWG/Emergency_Collection_Evacuation_Point_S2_ch.png');
insert into icon (id, name, url) values (4203, 'Emergency Collection Evacuation Point S3 ch',	'http://localhost/opencop-icons/HSWG/Emergency_Collection_Evacuation_Point_S3_ch.png');
insert into icon (id, name, url) values (4204, 'Emergency Collection Evacuation Point S4 ch',	'http://localhost/opencop-icons/HSWG/Emergency_Collection_Evacuation_Point_S4_ch.png');
insert into icon (id, name, url) values (4205, 'Emergency Incident Command Center S1',	'http://localhost/opencop-icons/HSWG/Emergency_Incident_Command_Center_S1.png');
insert into icon (id, name, url) values (4206, 'Emergency Incident Command Center S2',	'http://localhost/opencop-icons/HSWG/Emergency_Incident_Command_Center_S2.png');
insert into icon (id, name, url) values (4207, 'Emergency Incident Command Center S3',	'http://localhost/opencop-icons/HSWG/Emergency_Incident_Command_Center_S3.png');
insert into icon (id, name, url) values (4208, 'Emergency Incident Command Center S4',	'http://localhost/opencop-icons/HSWG/Emergency_Incident_Command_Center_S4.png');
insert into icon (id, name, url) values (4209, 'Emergency Operations Center S1',	'http://localhost/opencop-icons/HSWG/Emergency_Operations_Center_S1.png');
insert into icon (id, name, url) values (4210, 'Emergency Operations Center S2',	'http://localhost/opencop-icons/HSWG/Emergency_Operations_Center_S2.png');
insert into icon (id, name, url) values (4211, 'Emergency Operations Center S3',	'http://localhost/opencop-icons/HSWG/Emergency_Operations_Center_S3.png');
insert into icon (id, name, url) values (4212, 'Emergency Operations Center S4',	'http://localhost/opencop-icons/HSWG/Emergency_Operations_Center_S4.png');
insert into icon (id, name, url) values (4213, 'Emergency Operations Theme S1',	'http://localhost/opencop-icons/HSWG/Emergency_Operations_Theme_S1.png');
insert into icon (id, name, url) values (4214, 'Emergency Operations Theme S2',	'http://localhost/opencop-icons/HSWG/Emergency_Operations_Theme_S2.png');
insert into icon (id, name, url) values (4215, 'Emergency Operations Theme S3',	'http://localhost/opencop-icons/HSWG/Emergency_Operations_Theme_S3.png');
insert into icon (id, name, url) values (4216, 'Emergency Operations Theme S4',	'http://localhost/opencop-icons/HSWG/Emergency_Operations_Theme_S4.png');
insert into icon (id, name, url) values (4217, 'Emergency Public Information Center S1 ch',	'http://localhost/opencop-icons/HSWG/Emergency_Public_Information_Center_S1_ch.png');
insert into icon (id, name, url) values (4218, 'Emergency Public Information Center S1',	'http://localhost/opencop-icons/HSWG/Emergency_Public_Information_Center_S1.png');
insert into icon (id, name, url) values (4219, 'Emergency Public Information Center S2 ch',	'http://localhost/opencop-icons/HSWG/Emergency_Public_Information_Center_S2_ch.png');
insert into icon (id, name, url) values (4220, 'Emergency Public Information Center S3 ch',	'http://localhost/opencop-icons/HSWG/Emergency_Public_Information_Center_S3_ch.png');
insert into icon (id, name, url) values (4221, 'Emergency Public Information Center S4 ch',	'http://localhost/opencop-icons/HSWG/Emergency_Public_Information_Center_S4_ch.png');
insert into icon (id, name, url) values (4222, 'Emergency Public Service Center S1',	'http://localhost/opencop-icons/HSWG/Emergency_Public_Service_Center_S1.png');
insert into icon (id, name, url) values (4223, 'Emergency Shelters S1',	'http://localhost/opencop-icons/HSWG/Emergency_Shelters_S1.png');
insert into icon (id, name, url) values (4224, 'Emergency Shelters S2',	'http://localhost/opencop-icons/HSWG/Emergency_Shelters_S2.png');
insert into icon (id, name, url) values (4225, 'Emergency Shelters S3',	'http://localhost/opencop-icons/HSWG/Emergency_Shelters_S3.png');
insert into icon (id, name, url) values (4226, 'Emergency Shelters S4',	'http://localhost/opencop-icons/HSWG/Emergency_Shelters_S4.png');
insert into icon (id, name, url) values (4227, 'Emergency Staging Areas S1',	'http://localhost/opencop-icons/HSWG/Emergency_Staging_Areas_S1.png');
insert into icon (id, name, url) values (4228, 'Emergency Staging Areas S2',	'http://localhost/opencop-icons/HSWG/Emergency_Staging_Areas_S2.png');
insert into icon (id, name, url) values (4229, 'Emergency Staging Areas S3',	'http://localhost/opencop-icons/HSWG/Emergency_Staging_Areas_S3.png');
insert into icon (id, name, url) values (4230, 'Emergency Staging Areas S4',	'http://localhost/opencop-icons/HSWG/Emergency_Staging_Areas_S4.png');
insert into icon (id, name, url) values (4231, 'Emergency Teams S1',	'http://localhost/opencop-icons/HSWG/Emergency_Teams_S1.png');
insert into icon (id, name, url) values (4232, 'Emergency Teams S2',	'http://localhost/opencop-icons/HSWG/Emergency_Teams_S2.png');
insert into icon (id, name, url) values (4233, 'Emergency Teams S3',	'http://localhost/opencop-icons/HSWG/Emergency_Teams_S3.png');
insert into icon (id, name, url) values (4234, 'Emergency Teams S4',	'http://localhost/opencop-icons/HSWG/Emergency_Teams_S4.png');
insert into icon (id, name, url) values (4235, 'Emergency Water Distribution Center S1 ch',	'http://localhost/opencop-icons/HSWG/Emergency_Water_Distribution_Center_S1_ch.png');
insert into icon (id, name, url) values (4236, 'Emergency Water Distribution Center S1',	'http://localhost/opencop-icons/HSWG/Emergency_Water_Distribution_Center_S1.png');
insert into icon (id, name, url) values (4237, 'Emergency Water Distribution Center S2 ch',	'http://localhost/opencop-icons/HSWG/Emergency_Water_Distribution_Center_S2_ch.png');
insert into icon (id, name, url) values (4238, 'Emergency Water Distribution Center S3 ch',	'http://localhost/opencop-icons/HSWG/Emergency_Water_Distribution_Center_S3_ch.png');
insert into icon (id, name, url) values (4239, 'Emergency Water Distribution Center S4 ch',	'http://localhost/opencop-icons/HSWG/Emergency_Water_Distribution_Center_S4_ch.png');
insert into icon (id, name, url) values (4240, 'Emgergency Food Distribution Centers S1',	'http://localhost/opencop-icons/HSWG/Emgergency_Food_Distribution_Centers_S1.png');
insert into icon (id, name, url) values (4241, 'Emgergency Food Distribution Centers S2',	'http://localhost/opencop-icons/HSWG/Emgergency_Food_Distribution_Centers_S2.png');
insert into icon (id, name, url) values (4242, 'Emgergency Food Distribution Centers S3',	'http://localhost/opencop-icons/HSWG/Emgergency_Food_Distribution_Centers_S3.png');
insert into icon (id, name, url) values (4243, 'Emgergency Food Distribution Centers S4',	'http://localhost/opencop-icons/HSWG/Emgergency_Food_Distribution_Centers_S4.png');
insert into icon (id, name, url) values (4244, 'Energy Facilities Theme S1',	'http://localhost/opencop-icons/HSWG/Energy_Facilities_Theme_S1.png');
insert into icon (id, name, url) values (4245, 'Energy Facilities Theme S2',	'http://localhost/opencop-icons/HSWG/Energy_Facilities_Theme_S2.png');
insert into icon (id, name, url) values (4246, 'Energy Facilities Theme S3',	'http://localhost/opencop-icons/HSWG/Energy_Facilities_Theme_S3.png');
insert into icon (id, name, url) values (4247, 'Energy Facilities Theme S4',	'http://localhost/opencop-icons/HSWG/Energy_Facilities_Theme_S4.png');
insert into icon (id, name, url) values (4248, 'Energy Generation Stations S1',	'http://localhost/opencop-icons/HSWG/Energy_Generation_Stations_S1.png');
insert into icon (id, name, url) values (4249, 'Energy Generation Stations S2',	'http://localhost/opencop-icons/HSWG/Energy_Generation_Stations_S2.png');
insert into icon (id, name, url) values (4250, 'Energy Generation Stations S3',	'http://localhost/opencop-icons/HSWG/Energy_Generation_Stations_S3.png');
insert into icon (id, name, url) values (4251, 'Energy Generation Stations S4',	'http://localhost/opencop-icons/HSWG/Energy_Generation_Stations_S4.png');
insert into icon (id, name, url) values (4252, 'Energy Natural Gas Facilities S1',	'http://localhost/opencop-icons/HSWG/Energy_Natural_Gas_Facilities_S1.png');
insert into icon (id, name, url) values (4253, 'Energy Natural Gas Facilities S2',	'http://localhost/opencop-icons/HSWG/Energy_Natural_Gas_Facilities_S2.png');
insert into icon (id, name, url) values (4254, 'Energy Natural Gas Facilities S3',	'http://localhost/opencop-icons/HSWG/Energy_Natural_Gas_Facilities_S3.png');
insert into icon (id, name, url) values (4255, 'Energy Natural Gas Facilities S4',	'http://localhost/opencop-icons/HSWG/Energy_Natural_Gas_Facilities_S4.png');
insert into icon (id, name, url) values (4256, 'Energy Nuclear Facilities S1',	'http://localhost/opencop-icons/HSWG/Energy_Nuclear_Facilities_S1.png');
insert into icon (id, name, url) values (4257, 'Energy Nuclear Facilities S2',	'http://localhost/opencop-icons/HSWG/Energy_Nuclear_Facilities_S2.png');
insert into icon (id, name, url) values (4258, 'Energy Nuclear Facilities S3',	'http://localhost/opencop-icons/HSWG/Energy_Nuclear_Facilities_S3.png');
insert into icon (id, name, url) values (4259, 'Energy Nuclear Facilities S4',	'http://localhost/opencop-icons/HSWG/Energy_Nuclear_Facilities_S4.png');
insert into icon (id, name, url) values (4260, 'Energy Petroleum Facilities S1',	'http://localhost/opencop-icons/HSWG/Energy_Petroleum_Facilities_S1.png');
insert into icon (id, name, url) values (4261, 'Energy Petroleum Facilities S2',	'http://localhost/opencop-icons/HSWG/Energy_Petroleum_Facilities_S2.png');
insert into icon (id, name, url) values (4262, 'Energy Petroleum Facilities S3',	'http://localhost/opencop-icons/HSWG/Energy_Petroleum_Facilities_S3.png');
insert into icon (id, name, url) values (4263, 'Energy Petroleum Facilities S4',	'http://localhost/opencop-icons/HSWG/Energy_Petroleum_Facilities_S4.png');
insert into icon (id, name, url) values (4264, 'Energy Propane Facilities S1',	'http://localhost/opencop-icons/HSWG/Energy_Propane_Facilities_S1.png');
insert into icon (id, name, url) values (4265, 'Energy Propane Facilities S2',	'http://localhost/opencop-icons/HSWG/Energy_Propane_Facilities_S2.png');
insert into icon (id, name, url) values (4266, 'Energy Propane Facilities S3',	'http://localhost/opencop-icons/HSWG/Energy_Propane_Facilities_S3.png');
insert into icon (id, name, url) values (4267, 'Energy Propane Facilities S4',	'http://localhost/opencop-icons/HSWG/Energy_Propane_Facilities_S4.png');
insert into icon (id, name, url) values (4268, 'Fire Commercial Facility',	'http://localhost/opencop-icons/HSWG/Fire_Commercial_Facility.png');
insert into icon (id, name, url) values (4269, 'Fire Forest',	'http://localhost/opencop-icons/HSWG/Fire_Forest.png');
insert into icon (id, name, url) values (4270, 'Fire Grassland',	'http://localhost/opencop-icons/HSWG/Fire_Grassland.png');
insert into icon (id, name, url) values (4271, 'Fire Hotspot',	'http://localhost/opencop-icons/HSWG/Fire_Hotspot.png');
insert into icon (id, name, url) values (4272, 'Fire Hydrant S1',	'http://localhost/opencop-icons/HSWG/Fire_Hydrant_S1.png');
insert into icon (id, name, url) values (4273, 'Fire Hydrant S2',	'http://localhost/opencop-icons/HSWG/Fire_Hydrant_S2.png');
insert into icon (id, name, url) values (4274, 'Fire Hydrant S3',	'http://localhost/opencop-icons/HSWG/Fire_Hydrant_S3.png');
insert into icon (id, name, url) values (4275, 'Fire Hydrant S4',	'http://localhost/opencop-icons/HSWG/Fire_Hydrant_S4.png');
insert into icon (id, name, url) values (4276, 'Fire Industrial Facility',	'http://localhost/opencop-icons/HSWG/Fire_Industrial_Facility.png');
insert into icon (id, name, url) values (4277, 'Fire Non Residential ch',	'http://localhost/opencop-icons/HSWG/Fire_Non_Residential_ch.png');
insert into icon (id, name, url) values (4278, 'Fire Origin ch',	'http://localhost/opencop-icons/HSWG/Fire_Origin_ch.png');
insert into icon (id, name, url) values (4279, 'Fire Origin',	'http://localhost/opencop-icons/HSWG/Fire_Origin.png');
insert into icon (id, name, url) values (4280, 'Fire Other Water Supply Location S1',	'http://localhost/opencop-icons/HSWG/Fire_Other_Water_Supply_Location_S1.png');
insert into icon (id, name, url) values (4281, 'Fire Other Water Supply Location S2',	'http://localhost/opencop-icons/HSWG/Fire_Other_Water_Supply_Location_S2.png');
insert into icon (id, name, url) values (4282, 'Fire Other Water Supply Location S3',	'http://localhost/opencop-icons/HSWG/Fire_Other_Water_Supply_Location_S3.png');
insert into icon (id, name, url) values (4283, 'Fire Other Water Supply Location S4',	'http://localhost/opencop-icons/HSWG/Fire_Other_Water_Supply_Location_S4.png');
insert into icon (id, name, url) values (4284, 'Fire Residential ch',	'http://localhost/opencop-icons/HSWG/Fire_Residential_ch.png');
insert into icon (id, name, url) values (4285, 'Fire Residential',	'http://localhost/opencop-icons/HSWG/Fire_Residential.png');
insert into icon (id, name, url) values (4286, 'Fire School ch',	'http://localhost/opencop-icons/HSWG/Fire_School_ch.png');
insert into icon (id, name, url) values (4287, 'Fire Smoke ch',	'http://localhost/opencop-icons/HSWG/Fire_Smoke_ch.png');
insert into icon (id, name, url) values (4288, 'Fire Special Needs',	'http://localhost/opencop-icons/HSWG/Fire_Special_Needs.png');
insert into icon (id, name, url) values (4289, 'Fire Station S1',	'http://localhost/opencop-icons/HSWG/Fire_Station_S1.png');
insert into icon (id, name, url) values (4290, 'Fire Station S2',	'http://localhost/opencop-icons/HSWG/Fire_Station_S2.png');
insert into icon (id, name, url) values (4291, 'Fire Station S3',	'http://localhost/opencop-icons/HSWG/Fire_Station_S3.png');
insert into icon (id, name, url) values (4292, 'Fire Station S4',	'http://localhost/opencop-icons/HSWG/Fire_Station_S4.png');
insert into icon (id, name, url) values (4293, 'Fire Suppression Theme S1',	'http://localhost/opencop-icons/HSWG/Fire_Suppression_Theme_S1.png');
insert into icon (id, name, url) values (4294, 'Fire Suppression Theme S2',	'http://localhost/opencop-icons/HSWG/Fire_Suppression_Theme_S2.png');
insert into icon (id, name, url) values (4295, 'Fire Suppression Theme S3',	'http://localhost/opencop-icons/HSWG/Fire_Suppression_Theme_S3.png');
insert into icon (id, name, url) values (4296, 'Fire Suppression Theme S4',	'http://localhost/opencop-icons/HSWG/Fire_Suppression_Theme_S4.png');
insert into icon (id, name, url) values (4297, 'Fire Theme',	'http://localhost/opencop-icons/HSWG/Fire_Theme.png');
insert into icon (id, name, url) values (4298, 'Fire Wild ch',	'http://localhost/opencop-icons/HSWG/Fire_Wild_ch.png');
insert into icon (id, name, url) values (4299, 'Geo After Shock',	'http://localhost/opencop-icons/HSWG/Geo_After_Shock.png');
insert into icon (id, name, url) values (4300, 'Geo Avalanche ch',	'http://localhost/opencop-icons/HSWG/Geo_Avalanche_ch.png');
insert into icon (id, name, url) values (4301, 'Geo Avalanche',	'http://localhost/opencop-icons/HSWG/Geo_Avalanche.png');
insert into icon (id, name, url) values (4302, 'Geo Earth Quake Epicenter',	'http://localhost/opencop-icons/HSWG/Geo_Earth_Quake_Epicenter.png');
insert into icon (id, name, url) values (4303, 'Geo Landslide',	'http://localhost/opencop-icons/HSWG/Geo_Landslide.png');
insert into icon (id, name, url) values (4304, 'Geo Subsidence',	'http://localhost/opencop-icons/HSWG/Geo_Subsidence.png');
insert into icon (id, name, url) values (4305, 'Geo Volcanic Eruption',	'http://localhost/opencop-icons/HSWG/Geo_Volcanic_Eruption.png');
insert into icon (id, name, url) values (4306, 'Geo Volcanic Threat',	'http://localhost/opencop-icons/HSWG/Geo_Volcanic_Threat.png');
insert into icon (id, name, url) values (4307, 'Government Sites Theme S1',	'http://localhost/opencop-icons/HSWG/Government_Sites_Theme_S1.png');
insert into icon (id, name, url) values (4308, 'Government Sites Theme S2',	'http://localhost/opencop-icons/HSWG/Government_Sites_Theme_S2.png');
insert into icon (id, name, url) values (4309, 'Government Sites Theme S3',	'http://localhost/opencop-icons/HSWG/Government_Sites_Theme_S3.png');
insert into icon (id, name, url) values (4310, 'Government Sites Theme S4',	'http://localhost/opencop-icons/HSWG/Government_Sites_Theme_S4.png');
insert into icon (id, name, url) values (4311, 'Hazmat Chemical Agents',	'http://localhost/opencop-icons/HSWG/Hazmat_Chemical_Agents.png');
insert into icon (id, name, url) values (4312, 'Hazmat Corrosive Material',	'http://localhost/opencop-icons/HSWG/Hazmat_Corrosive_Material.png');
insert into icon (id, name, url) values (4313, 'Hazmat Dangerous When Wet',	'http://localhost/opencop-icons/HSWG/Hazmat_Dangerous_When_Wet.png');
insert into icon (id, name, url) values (4314, 'Hazmat Explosive',	'http://localhost/opencop-icons/HSWG/Hazmat_Explosive.png');
insert into icon (id, name, url) values (4315, 'Hazmat Flammable Gas',	'http://localhost/opencop-icons/HSWG/Hazmat_Flammable_Gas.png');
insert into icon (id, name, url) values (4316, 'Hazmat Flammable Liquid',	'http://localhost/opencop-icons/HSWG/Hazmat_Flammable_Liquid.png');
insert into icon (id, name, url) values (4317, 'Hazmat Flammable Solid',	'http://localhost/opencop-icons/HSWG/Hazmat_Flammable_Solid.png');
insert into icon (id, name, url) values (4318, 'Hazmat Hazardous Theme',	'http://localhost/opencop-icons/HSWG/Hazmat_Hazardous_Theme.png');
insert into icon (id, name, url) values (4319, 'Hazmat Non-Flammable Gas',	'http://localhost/opencop-icons/HSWG/Hazmat_Non-Flammable_Gas.png');
insert into icon (id, name, url) values (4320, 'Hazmat Organic Peroxides',	'http://localhost/opencop-icons/HSWG/Hazmat_Organic_Peroxides.png');
insert into icon (id, name, url) values (4321, 'Hazmat Oxidizers',	'http://localhost/opencop-icons/HSWG/Hazmat_Oxidizers.png');
insert into icon (id, name, url) values (4322, 'Hazmat Radioactive Material ch',	'http://localhost/opencop-icons/HSWG/Hazmat_Radioactive_Material_ch.png');
insert into icon (id, name, url) values (4323, 'Hazmat Spontaneously Combustible',	'http://localhost/opencop-icons/HSWG/Hazmat_Spontaneously_Combustible.png');
insert into icon (id, name, url) values (4324, 'Hazmat Toxic and Infectious',	'http://localhost/opencop-icons/HSWG/Hazmat_Toxic_and_Infectious.png');
insert into icon (id, name, url) values (4325, 'Hazmat Toxic Gas',	'http://localhost/opencop-icons/HSWG/Hazmat_Toxic_Gas.png');
insert into icon (id, name, url) values (4326, 'Hazmat Unexploded Ordnance',	'http://localhost/opencop-icons/HSWG/Hazmat_Unexploded_Ordnance.png');
insert into icon (id, name, url) values (4327, 'hswg ref nav header roll r1 c1',	'http://localhost/opencop-icons/HSWG/hswg_ref_nav_header_roll_r1_c1.png');
insert into icon (id, name, url) values (4328, 'hswg ref nav header roll r2 c10',	'http://localhost/opencop-icons/HSWG/hswg_ref_nav_header_roll_r2_c10.png');
insert into icon (id, name, url) values (4329, 'hswg ref nav header roll r2 c12',	'http://localhost/opencop-icons/HSWG/hswg_ref_nav_header_roll_r2_c12.png');
insert into icon (id, name, url) values (4330, 'hswg ref nav header roll r2 c14',	'http://localhost/opencop-icons/HSWG/hswg_ref_nav_header_roll_r2_c14.png');
insert into icon (id, name, url) values (4331, 'hswg ref nav header roll r2 c16',	'http://localhost/opencop-icons/HSWG/hswg_ref_nav_header_roll_r2_c16.png');
insert into icon (id, name, url) values (4332, 'hswg ref nav header roll r2 c18',	'http://localhost/opencop-icons/HSWG/hswg_ref_nav_header_roll_r2_c18.png');
insert into icon (id, name, url) values (4333, 'hswg ref nav header roll r2 c1',	'http://localhost/opencop-icons/HSWG/hswg_ref_nav_header_roll_r2_c1.png');
insert into icon (id, name, url) values (4334, 'hswg ref nav header roll r2 c20',	'http://localhost/opencop-icons/HSWG/hswg_ref_nav_header_roll_r2_c20.png');
insert into icon (id, name, url) values (4335, 'hswg ref nav header roll r2 c22',	'http://localhost/opencop-icons/HSWG/hswg_ref_nav_header_roll_r2_c22.png');
insert into icon (id, name, url) values (4336, 'hswg ref nav header roll r2 c2',	'http://localhost/opencop-icons/HSWG/hswg_ref_nav_header_roll_r2_c2.png');
insert into icon (id, name, url) values (4337, 'hswg ref nav header roll r2 c4',	'http://localhost/opencop-icons/HSWG/hswg_ref_nav_header_roll_r2_c4.png');
insert into icon (id, name, url) values (4338, 'hswg ref nav header roll r2 c6',	'http://localhost/opencop-icons/HSWG/hswg_ref_nav_header_roll_r2_c6.png');
insert into icon (id, name, url) values (4339, 'hswg ref nav header roll r2 c8',	'http://localhost/opencop-icons/HSWG/hswg_ref_nav_header_roll_r2_c8.png');
insert into icon (id, name, url) values (4340, 'Hydro Meteor Drizzle',	'http://localhost/opencop-icons/HSWG/Hydro_Meteor_Drizzle.png');
insert into icon (id, name, url) values (4341, 'Hydro Meteor Drought',	'http://localhost/opencop-icons/HSWG/Hydro_Meteor_Drought.png');
insert into icon (id, name, url) values (4342, 'Hydro Meteor Flood',	'http://localhost/opencop-icons/HSWG/Hydro_Meteor_Flood.png');
insert into icon (id, name, url) values (4343, 'Hydro Meteor Fog',	'http://localhost/opencop-icons/HSWG/Hydro_Meteor_Fog.png');
insert into icon (id, name, url) values (4344, 'Hydro Meteor Hail',	'http://localhost/opencop-icons/HSWG/Hydro_Meteor_Hail.png');
insert into icon (id, name, url) values (4345, 'Hydro Meteor Inversion',	'http://localhost/opencop-icons/HSWG/Hydro_Meteor_Inversion.png');
insert into icon (id, name, url) values (4346, 'Hydro Meteor Rain',	'http://localhost/opencop-icons/HSWG/Hydro_Meteor_Rain.png');
insert into icon (id, name, url) values (4347, 'Hydro Meteor Sand Dust Storm',	'http://localhost/opencop-icons/HSWG/Hydro_Meteor_Sand_Dust_Storm.png');
insert into icon (id, name, url) values (4348, 'Hydro Meteor Snow',	'http://localhost/opencop-icons/HSWG/Hydro_Meteor_Snow.png');
insert into icon (id, name, url) values (4349, 'Hydro Meteor Thunder Storm',	'http://localhost/opencop-icons/HSWG/Hydro_Meteor_Thunder_Storm.png');
insert into icon (id, name, url) values (4350, 'Hydro Meteor Tornado ch',	'http://localhost/opencop-icons/HSWG/Hydro_Meteor_Tornado_ch.png');
insert into icon (id, name, url) values (4351, 'Hydro Meteor Tropical Cyclone',	'http://localhost/opencop-icons/HSWG/Hydro_Meteor_Tropical_Cyclone.png');
insert into icon (id, name, url) values (4352, 'Hydro Meteor Tsunami ch',	'http://localhost/opencop-icons/HSWG/Hydro_Meteor_Tsunami_ch.png');
insert into icon (id, name, url) values (4353, 'Incident',	'http://localhost/opencop-icons/HSWG/Incident.png');
insert into icon (id, name, url) values (4354, 'Infestation Bird ch',	'http://localhost/opencop-icons/HSWG/Infestation_Bird_ch.png');
insert into icon (id, name, url) values (4355, 'Infestation Insect',	'http://localhost/opencop-icons/HSWG/Infestation_Insect.png');
insert into icon (id, name, url) values (4356, 'Infestation Microbial',	'http://localhost/opencop-icons/HSWG/Infestation_Microbial.png');
insert into icon (id, name, url) values (4357, 'Infestation Reptile ch',	'http://localhost/opencop-icons/HSWG/Infestation_Reptile_ch.png');
insert into icon (id, name, url) values (4358, 'Infestation Rodent',	'http://localhost/opencop-icons/HSWG/Infestation_Rodent.png');
insert into icon (id, name, url) values (4359, 'Infrastructure S1',	'http://localhost/opencop-icons/HSWG/Infrastructure_S1.png');
insert into icon (id, name, url) values (4360, 'Infrastructure S2',	'http://localhost/opencop-icons/HSWG/Infrastructure_S2.png');
insert into icon (id, name, url) values (4361, 'Infrastructure S3',	'http://localhost/opencop-icons/HSWG/Infrastructure_S3.png');
insert into icon (id, name, url) values (4362, 'Infrastructure S4',	'http://localhost/opencop-icons/HSWG/Infrastructure_S4.png');
insert into icon (id, name, url) values (4363, 'Law ATF S1',	'http://localhost/opencop-icons/HSWG/Law_ATF_S1.png');
insert into icon (id, name, url) values (4364, 'Law ATF S2',	'http://localhost/opencop-icons/HSWG/Law_ATF_S2.png');
insert into icon (id, name, url) values (4365, 'Law ATF S3',	'http://localhost/opencop-icons/HSWG/Law_ATF_S3.png');
insert into icon (id, name, url) values (4366, 'Law ATF S4',	'http://localhost/opencop-icons/HSWG/Law_ATF_S4.png');
insert into icon (id, name, url) values (4367, 'Law Border Patrol S1',	'http://localhost/opencop-icons/HSWG/Law_Border_Patrol_S1.png');
insert into icon (id, name, url) values (4368, 'Law Border Patrol S2',	'http://localhost/opencop-icons/HSWG/Law_Border_Patrol_S2.png');
insert into icon (id, name, url) values (4369, 'Law Border Patrol S3',	'http://localhost/opencop-icons/HSWG/Law_Border_Patrol_S3.png');
insert into icon (id, name, url) values (4370, 'Law Border Patrol S4',	'http://localhost/opencop-icons/HSWG/Law_Border_Patrol_S4.png');
insert into icon (id, name, url) values (4371, 'Law Customs Service S1',	'http://localhost/opencop-icons/HSWG/Law_Customs_Service_S1.png');
insert into icon (id, name, url) values (4372, 'Law Customs Service S2',	'http://localhost/opencop-icons/HSWG/Law_Customs_Service_S2.png');
insert into icon (id, name, url) values (4373, 'Law Customs Service S3',	'http://localhost/opencop-icons/HSWG/Law_Customs_Service_S3.png');
insert into icon (id, name, url) values (4374, 'Law Customs Service S4',	'http://localhost/opencop-icons/HSWG/Law_Customs_Service_S4.png');
insert into icon (id, name, url) values (4375, 'Law DEA S1',	'http://localhost/opencop-icons/HSWG/Law_DEA_S1.png');
insert into icon (id, name, url) values (4376, 'Law DEA S2',	'http://localhost/opencop-icons/HSWG/Law_DEA_S2.png');
insert into icon (id, name, url) values (4377, 'Law DEA S3',	'http://localhost/opencop-icons/HSWG/Law_DEA_S3.png');
insert into icon (id, name, url) values (4378, 'Law DEA S4',	'http://localhost/opencop-icons/HSWG/Law_DEA_S4.png');
insert into icon (id, name, url) values (4379, 'Law DOJ S1',	'http://localhost/opencop-icons/HSWG/Law_DOJ_S1.png');
insert into icon (id, name, url) values (4380, 'Law DOJ S2',	'http://localhost/opencop-icons/HSWG/Law_DOJ_S2.png');
insert into icon (id, name, url) values (4381, 'Law DOJ S3',	'http://localhost/opencop-icons/HSWG/Law_DOJ_S3.png');
insert into icon (id, name, url) values (4382, 'Law DOJ S4',	'http://localhost/opencop-icons/HSWG/Law_DOJ_S4.png');
insert into icon (id, name, url) values (4383, 'Law Enforcement Theme S1',	'http://localhost/opencop-icons/HSWG/Law_Enforcement_Theme_S1.png');
insert into icon (id, name, url) values (4384, 'Law Enforcement Theme S2',	'http://localhost/opencop-icons/HSWG/Law_Enforcement_Theme_S2.png');
insert into icon (id, name, url) values (4385, 'Law Enforcement Theme S3',	'http://localhost/opencop-icons/HSWG/Law_Enforcement_Theme_S3.png');
insert into icon (id, name, url) values (4386, 'Law Enforcement Theme S4',	'http://localhost/opencop-icons/HSWG/Law_Enforcement_Theme_S4.png');
insert into icon (id, name, url) values (4387, 'Law FBI S1',	'http://localhost/opencop-icons/HSWG/Law_FBI_S1.png');
insert into icon (id, name, url) values (4388, 'Law FBI S2',	'http://localhost/opencop-icons/HSWG/Law_FBI_S2.png');
insert into icon (id, name, url) values (4389, 'Law FBI S3',	'http://localhost/opencop-icons/HSWG/Law_FBI_S3.png');
insert into icon (id, name, url) values (4390, 'Law FBI S4',	'http://localhost/opencop-icons/HSWG/Law_FBI_S4.png');
insert into icon (id, name, url) values (4391, 'Law Police S1',	'http://localhost/opencop-icons/HSWG/Law_Police_S1.png');
insert into icon (id, name, url) values (4392, 'Law Police S2',	'http://localhost/opencop-icons/HSWG/Law_Police_S2.png');
insert into icon (id, name, url) values (4393, 'Law Police S3',	'http://localhost/opencop-icons/HSWG/Law_Police_S3.png');
insert into icon (id, name, url) values (4394, 'Law Police S4',	'http://localhost/opencop-icons/HSWG/Law_Police_S4.png');
insert into icon (id, name, url) values (4395, 'Law Prison S1',	'http://localhost/opencop-icons/HSWG/Law_Prison_S1.png');
insert into icon (id, name, url) values (4396, 'Law Prison S2',	'http://localhost/opencop-icons/HSWG/Law_Prison_S2.png');
insert into icon (id, name, url) values (4397, 'Law Prison S3',	'http://localhost/opencop-icons/HSWG/Law_Prison_S3.png');
insert into icon (id, name, url) values (4398, 'Law Prison S4',	'http://localhost/opencop-icons/HSWG/Law_Prison_S4.png');
insert into icon (id, name, url) values (4399, 'Law Secret Service S1',	'http://localhost/opencop-icons/HSWG/Law_Secret_Service_S1.png');
insert into icon (id, name, url) values (4400, 'Law Secret Service S2',	'http://localhost/opencop-icons/HSWG/Law_Secret_Service_S2.png');
insert into icon (id, name, url) values (4401, 'Law Secret Service S3',	'http://localhost/opencop-icons/HSWG/Law_Secret_Service_S3.png');
insert into icon (id, name, url) values (4402, 'Law Secret Service S4',	'http://localhost/opencop-icons/HSWG/Law_Secret_Service_S4.png');
insert into icon (id, name, url) values (4403, 'Law TSA S1',	'http://localhost/opencop-icons/HSWG/Law_TSA_S1.png');
insert into icon (id, name, url) values (4404, 'Law TSA S2',	'http://localhost/opencop-icons/HSWG/Law_TSA_S2.png');
insert into icon (id, name, url) values (4405, 'Law TSA S3',	'http://localhost/opencop-icons/HSWG/Law_TSA_S3.png');
insert into icon (id, name, url) values (4406, 'Law TSA S4',	'http://localhost/opencop-icons/HSWG/Law_TSA_S4.png');
insert into icon (id, name, url) values (4407, 'Law US Coast Guard S1',	'http://localhost/opencop-icons/HSWG/Law_US_Coast_Guard_S1.png');
insert into icon (id, name, url) values (4408, 'Law US Coast Guard S2',	'http://localhost/opencop-icons/HSWG/Law_US_Coast_Guard_S2.png');
insert into icon (id, name, url) values (4409, 'Law US Coast Guard S3',	'http://localhost/opencop-icons/HSWG/Law_US_Coast_Guard_S3.png');
insert into icon (id, name, url) values (4410, 'Law US Coast Guard S4',	'http://localhost/opencop-icons/HSWG/Law_US_Coast_Guard_S4.png');
insert into icon (id, name, url) values (4411, 'Law US Marshall S1',	'http://localhost/opencop-icons/HSWG/Law_US_Marshall_S1.png');
insert into icon (id, name, url) values (4412, 'Law US Marshall S2',	'http://localhost/opencop-icons/HSWG/Law_US_Marshall_S2.png');
insert into icon (id, name, url) values (4413, 'Law US Marshall S3',	'http://localhost/opencop-icons/HSWG/Law_US_Marshall_S3.png');
insert into icon (id, name, url) values (4414, 'Law US Marshall S4',	'http://localhost/opencop-icons/HSWG/Law_US_Marshall_S4.png');
insert into icon (id, name, url) values (4415, 'Military Armory S1',	'http://localhost/opencop-icons/HSWG/Military_Armory_S1.png');
insert into icon (id, name, url) values (4416, 'Military Armory S2',	'http://localhost/opencop-icons/HSWG/Military_Armory_S2.png');
insert into icon (id, name, url) values (4417, 'Military Armory S3',	'http://localhost/opencop-icons/HSWG/Military_Armory_S3.png');
insert into icon (id, name, url) values (4418, 'Military Armory S4',	'http://localhost/opencop-icons/HSWG/Military_Armory_S4.png');
insert into icon (id, name, url) values (4419, 'Military Base S1',	'http://localhost/opencop-icons/HSWG/Military_Base_S1.png');
insert into icon (id, name, url) values (4420, 'Military Base S2',	'http://localhost/opencop-icons/HSWG/Military_Base_S2.png');
insert into icon (id, name, url) values (4421, 'Military Base S3',	'http://localhost/opencop-icons/HSWG/Military_Base_S3.png');
insert into icon (id, name, url) values (4422, 'Military Base S4',	'http://localhost/opencop-icons/HSWG/Military_Base_S4.png');
insert into icon (id, name, url) values (4423, 'Military Infrastructure Theme S1',	'http://localhost/opencop-icons/HSWG/Military_Infrastructure_Theme_S1.png');
insert into icon (id, name, url) values (4424, 'Military Infrastructure Theme S2',	'http://localhost/opencop-icons/HSWG/Military_Infrastructure_Theme_S2.png');
insert into icon (id, name, url) values (4425, 'Military Infrastructure Theme S3',	'http://localhost/opencop-icons/HSWG/Military_Infrastructure_Theme_S3.png');
insert into icon (id, name, url) values (4426, 'Military Infrastructure Theme S4',	'http://localhost/opencop-icons/HSWG/Military_Infrastructure_Theme_S4.png');
insert into icon (id, name, url) values (4427, 'Natural Event',	'http://localhost/opencop-icons/HSWG/Natural_Event.png');
insert into icon (id, name, url) values (4428, 'Operation S1',	'http://localhost/opencop-icons/HSWG/Operation_S1.png');
insert into icon (id, name, url) values (4429, 'Operation S2',	'http://localhost/opencop-icons/HSWG/Operation_S2.png');
insert into icon (id, name, url) values (4430, 'Operation S3',	'http://localhost/opencop-icons/HSWG/Operation_S3.png');
insert into icon (id, name, url) values (4431, 'Operation S4',	'http://localhost/opencop-icons/HSWG/Operation_S4.png');
insert into icon (id, name, url) values (4432, 'Postal Distribution Center S1',	'http://localhost/opencop-icons/HSWG/Postal_Distribution_Center_S1.png');
insert into icon (id, name, url) values (4433, 'Postal Distribution Center S2',	'http://localhost/opencop-icons/HSWG/Postal_Distribution_Center_S2.png');
insert into icon (id, name, url) values (4434, 'Postal Distribution Center S3',	'http://localhost/opencop-icons/HSWG/Postal_Distribution_Center_S3.png');
insert into icon (id, name, url) values (4435, 'Postal Distribution Center S4',	'http://localhost/opencop-icons/HSWG/Postal_Distribution_Center_S4.png');
insert into icon (id, name, url) values (4436, 'Postal Post Office S1',	'http://localhost/opencop-icons/HSWG/Postal_Post_Office_S1.png');
insert into icon (id, name, url) values (4437, 'Postal Post Office S2',	'http://localhost/opencop-icons/HSWG/Postal_Post_Office_S2.png');
insert into icon (id, name, url) values (4438, 'Postal Post Office S3',	'http://localhost/opencop-icons/HSWG/Postal_Post_Office_S3.png');
insert into icon (id, name, url) values (4439, 'Postal Post Office S4',	'http://localhost/opencop-icons/HSWG/Postal_Post_Office_S4.png');
insert into icon (id, name, url) values (4440, 'Postal Service Theme S1',	'http://localhost/opencop-icons/HSWG/Postal_Service_Theme_S1.png');
insert into icon (id, name, url) values (4441, 'Postal Service Theme S2',	'http://localhost/opencop-icons/HSWG/Postal_Service_Theme_S2.png');
insert into icon (id, name, url) values (4442, 'Postal Service Theme S3',	'http://localhost/opencop-icons/HSWG/Postal_Service_Theme_S3.png');
insert into icon (id, name, url) values (4443, 'Postal Service Theme S4',	'http://localhost/opencop-icons/HSWG/Postal_Service_Theme_S4.png');
insert into icon (id, name, url) values (4444, 'Public Venue Church S1',	'http://localhost/opencop-icons/HSWG/Public_Venue_Church_S1.png');
insert into icon (id, name, url) values (4445, 'Public Venue Enclosed Facility S1',	'http://localhost/opencop-icons/HSWG/Public_Venue_Enclosed_Facility_S1.png');
insert into icon (id, name, url) values (4446, 'Public Venue Enclosed Facility S2',	'http://localhost/opencop-icons/HSWG/Public_Venue_Enclosed_Facility_S2.png');
insert into icon (id, name, url) values (4447, 'Public Venue Enclosed Facility S3',	'http://localhost/opencop-icons/HSWG/Public_Venue_Enclosed_Facility_S3.png');
insert into icon (id, name, url) values (4448, 'Public Venue Enclosed Facility S4',	'http://localhost/opencop-icons/HSWG/Public_Venue_Enclosed_Facility_S4.png');
insert into icon (id, name, url) values (4449, 'Public Venue Mosque S1',	'http://localhost/opencop-icons/HSWG/Public_Venue_Mosque_S1.png');
insert into icon (id, name, url) values (4450, 'Public Venue Open Facility S1',	'http://localhost/opencop-icons/HSWG/Public_Venue_Open_Facility_S1.png');
insert into icon (id, name, url) values (4451, 'Public Venue Open Facility S2',	'http://localhost/opencop-icons/HSWG/Public_Venue_Open_Facility_S2.png');
insert into icon (id, name, url) values (4452, 'Public Venue Open Facility S3',	'http://localhost/opencop-icons/HSWG/Public_Venue_Open_Facility_S3.png');
insert into icon (id, name, url) values (4453, 'Public Venue Open Facility S4',	'http://localhost/opencop-icons/HSWG/Public_Venue_Open_Facility_S4.png');
insert into icon (id, name, url) values (4454, 'Public Venue Recreational Area S1',	'http://localhost/opencop-icons/HSWG/Public_Venue_Recreational_Area_S1.png');
insert into icon (id, name, url) values (4455, 'Public Venue Recreational Area S2',	'http://localhost/opencop-icons/HSWG/Public_Venue_Recreational_Area_S2.png');
insert into icon (id, name, url) values (4456, 'Public Venue Recreational Area S3',	'http://localhost/opencop-icons/HSWG/Public_Venue_Recreational_Area_S3.png');
insert into icon (id, name, url) values (4457, 'Public Venue Recreational Area S4',	'http://localhost/opencop-icons/HSWG/Public_Venue_Recreational_Area_S4.png');
insert into icon (id, name, url) values (4458, 'Public Venue Religious Institution S1',	'http://localhost/opencop-icons/HSWG/Public_Venue_Religious_Institution_S1.png');
insert into icon (id, name, url) values (4459, 'Public Venue Religious Institution S2',	'http://localhost/opencop-icons/HSWG/Public_Venue_Religious_Institution_S2.png');
insert into icon (id, name, url) values (4460, 'Public Venue Religious Institution S3',	'http://localhost/opencop-icons/HSWG/Public_Venue_Religious_Institution_S3.png');
insert into icon (id, name, url) values (4461, 'Public Venue Religious Institution S4',	'http://localhost/opencop-icons/HSWG/Public_Venue_Religious_Institution_S4.png');
insert into icon (id, name, url) values (4462, 'Public Venues Theme S1',	'http://localhost/opencop-icons/HSWG/Public_Venues_Theme_S1.png');
insert into icon (id, name, url) values (4463, 'Public Venues Theme S2',	'http://localhost/opencop-icons/HSWG/Public_Venues_Theme_S2.png');
insert into icon (id, name, url) values (4464, 'Public Venues Theme S3',	'http://localhost/opencop-icons/HSWG/Public_Venues_Theme_S3.png');
insert into icon (id, name, url) values (4465, 'Public Venues Theme S4',	'http://localhost/opencop-icons/HSWG/Public_Venues_Theme_S4.png');
insert into icon (id, name, url) values (4466, 'Public Venue Synagogue S1',	'http://localhost/opencop-icons/HSWG/Public_Venue_Synagogue_S1.png');
insert into icon (id, name, url) values (4467, 'Public Venue Temple S1',	'http://localhost/opencop-icons/HSWG/Public_Venue_Temple_S1.png');
insert into icon (id, name, url) values (4468, 'Sensor Biological S1',	'http://localhost/opencop-icons/HSWG/Sensor_Biological_S1.png');
insert into icon (id, name, url) values (4469, 'Sensor Biological S2',	'http://localhost/opencop-icons/HSWG/Sensor_Biological_S2.png');
insert into icon (id, name, url) values (4470, 'Sensor Biological S3',	'http://localhost/opencop-icons/HSWG/Sensor_Biological_S3.png');
insert into icon (id, name, url) values (4471, 'Sensor Biological S4',	'http://localhost/opencop-icons/HSWG/Sensor_Biological_S4.png');
insert into icon (id, name, url) values (4472, 'Sensor Chemical S1',	'http://localhost/opencop-icons/HSWG/Sensor_Chemical_S1.png');
insert into icon (id, name, url) values (4473, 'Sensor Chemical S2',	'http://localhost/opencop-icons/HSWG/Sensor_Chemical_S2.png');
insert into icon (id, name, url) values (4474, 'Sensor Chemical S3',	'http://localhost/opencop-icons/HSWG/Sensor_Chemical_S3.png');
insert into icon (id, name, url) values (4475, 'Sensor Chemical S4',	'http://localhost/opencop-icons/HSWG/Sensor_Chemical_S4.png');
insert into icon (id, name, url) values (4476, 'Sensor Intrusion S1',	'http://localhost/opencop-icons/HSWG/Sensor_Intrusion_S1.png');
insert into icon (id, name, url) values (4477, 'Sensor Intrusion S2',	'http://localhost/opencop-icons/HSWG/Sensor_Intrusion_S2.png');
insert into icon (id, name, url) values (4478, 'Sensor Intrusion S3',	'http://localhost/opencop-icons/HSWG/Sensor_Intrusion_S3.png');
insert into icon (id, name, url) values (4479, 'Sensor Intrusion S4',	'http://localhost/opencop-icons/HSWG/Sensor_Intrusion_S4.png');
insert into icon (id, name, url) values (4480, 'Sensor Nuclear S1',	'http://localhost/opencop-icons/HSWG/Sensor_Nuclear_S1.png');
insert into icon (id, name, url) values (4481, 'Sensor Nuclear S2',	'http://localhost/opencop-icons/HSWG/Sensor_Nuclear_S2.png');
insert into icon (id, name, url) values (4482, 'Sensor Nuclear S3',	'http://localhost/opencop-icons/HSWG/Sensor_Nuclear_S3.png');
insert into icon (id, name, url) values (4483, 'Sensor Nuclear S4',	'http://localhost/opencop-icons/HSWG/Sensor_Nuclear_S4.png');
insert into icon (id, name, url) values (4484, 'Sensor Radiological S1 ch',	'http://localhost/opencop-icons/HSWG/Sensor_Radiological_S1_ch.png');
insert into icon (id, name, url) values (4485, 'Sensor Radiological S2 ch',	'http://localhost/opencop-icons/HSWG/Sensor_Radiological_S2_ch.png');
insert into icon (id, name, url) values (4486, 'Sensor Radiological S3 ch',	'http://localhost/opencop-icons/HSWG/Sensor_Radiological_S3_ch.png');
insert into icon (id, name, url) values (4487, 'Sensor Radiological S4 ch',	'http://localhost/opencop-icons/HSWG/Sensor_Radiological_S4_ch.png');
insert into icon (id, name, url) values (4488, 'Sensors Theme S1',	'http://localhost/opencop-icons/HSWG/Sensors_Theme_S1.png');
insert into icon (id, name, url) values (4489, 'Sensors Theme S2',	'http://localhost/opencop-icons/HSWG/Sensors_Theme_S2.png');
insert into icon (id, name, url) values (4490, 'Sensors Theme S3',	'http://localhost/opencop-icons/HSWG/Sensors_Theme_S3.png');
insert into icon (id, name, url) values (4491, 'Sensors Theme S4',	'http://localhost/opencop-icons/HSWG/Sensors_Theme_S4.png');
insert into icon (id, name, url) values (4492, 'Special Needs Adult Day Care S1',	'http://localhost/opencop-icons/HSWG/Special_Needs_Adult_Day_Care_S1.png');
insert into icon (id, name, url) values (4493, 'Special Needs Adult Day Care S2',	'http://localhost/opencop-icons/HSWG/Special_Needs_Adult_Day_Care_S2.png');
insert into icon (id, name, url) values (4494, 'Special Needs Adult Day Care S3',	'http://localhost/opencop-icons/HSWG/Special_Needs_Adult_Day_Care_S3.png');
insert into icon (id, name, url) values (4495, 'Special Needs Adult Day Care S4',	'http://localhost/opencop-icons/HSWG/Special_Needs_Adult_Day_Care_S4.png');
insert into icon (id, name, url) values (4496, 'Special Needs Child Day Care S1',	'http://localhost/opencop-icons/HSWG/Special_Needs_Child_Day_Care_S1.png');
insert into icon (id, name, url) values (4497, 'Special Needs Child Day Care S2',	'http://localhost/opencop-icons/HSWG/Special_Needs_Child_Day_Care_S2.png');
insert into icon (id, name, url) values (4498, 'Special Needs Child Day Care S3',	'http://localhost/opencop-icons/HSWG/Special_Needs_Child_Day_Care_S3.png');
insert into icon (id, name, url) values (4499, 'Special Needs Child Day Care S4',	'http://localhost/opencop-icons/HSWG/Special_Needs_Child_Day_Care_S4.png');
insert into icon (id, name, url) values (4500, 'Special Needs Elder Care S1',	'http://localhost/opencop-icons/HSWG/Special_Needs_Elder_Care_S1.png');
insert into icon (id, name, url) values (4501, 'Special Needs Elder Care S2',	'http://localhost/opencop-icons/HSWG/Special_Needs_Elder_Care_S2.png');
insert into icon (id, name, url) values (4502, 'Special Needs Elder Care S3',	'http://localhost/opencop-icons/HSWG/Special_Needs_Elder_Care_S3.png');
insert into icon (id, name, url) values (4503, 'Special Needs Elder Care S4',	'http://localhost/opencop-icons/HSWG/Special_Needs_Elder_Care_S4.png');
insert into icon (id, name, url) values (4504, 'Special Needs Theme S1',	'http://localhost/opencop-icons/HSWG/Special_Needs_Theme_S1.png');
insert into icon (id, name, url) values (4505, 'Special Needs Theme S2',	'http://localhost/opencop-icons/HSWG/Special_Needs_Theme_S2.png');
insert into icon (id, name, url) values (4506, 'Special Needs Theme S3',	'http://localhost/opencop-icons/HSWG/Special_Needs_Theme_S3.png');
insert into icon (id, name, url) values (4507, 'Special Needs Theme S4',	'http://localhost/opencop-icons/HSWG/Special_Needs_Theme_S4.png');
insert into icon (id, name, url) values (4508, 'symbolsizesuggestion',	'http://localhost/opencop-icons/HSWG/symbolsizesuggestion.png');
insert into icon (id, name, url) values (4509, 'Telecommunications Facility S1',	'http://localhost/opencop-icons/HSWG/Telecommunications_Facility_S1.png');
insert into icon (id, name, url) values (4510, 'Telecommunications Facility S2',	'http://localhost/opencop-icons/HSWG/Telecommunications_Facility_S2.png');
insert into icon (id, name, url) values (4511, 'Telecommunications Facility S3',	'http://localhost/opencop-icons/HSWG/Telecommunications_Facility_S3.png');
insert into icon (id, name, url) values (4512, 'Telecommunications Facility S4',	'http://localhost/opencop-icons/HSWG/Telecommunications_Facility_S4.png');
insert into icon (id, name, url) values (4513, 'Telecommunications Theme S1',	'http://localhost/opencop-icons/HSWG/Telecommunications_Theme_S1.png');
insert into icon (id, name, url) values (4514, 'Telecommunications Theme S2',	'http://localhost/opencop-icons/HSWG/Telecommunications_Theme_S2.png');
insert into icon (id, name, url) values (4515, 'Telecommunications Theme S3',	'http://localhost/opencop-icons/HSWG/Telecommunications_Theme_S3.png');
insert into icon (id, name, url) values (4516, 'Telecommunications Theme S4',	'http://localhost/opencop-icons/HSWG/Telecommunications_Theme_S4.png');
insert into icon (id, name, url) values (4517, 'Telecommunications Tower S1',	'http://localhost/opencop-icons/HSWG/Telecommunications_Tower_S1.png');
insert into icon (id, name, url) values (4518, 'Telecommunications Tower S2',	'http://localhost/opencop-icons/HSWG/Telecommunications_Tower_S2.png');
insert into icon (id, name, url) values (4519, 'Telecommunications Tower S3',	'http://localhost/opencop-icons/HSWG/Telecommunications_Tower_S3.png');
insert into icon (id, name, url) values (4520, 'Telecommunications Tower S4',	'http://localhost/opencop-icons/HSWG/Telecommunications_Tower_S4.png');
insert into icon (id, name, url) values (4521, 'Trans Airport S1',	'http://localhost/opencop-icons/HSWG/Trans_Airport_S1.png');
insert into icon (id, name, url) values (4522, 'Trans Airport S2',	'http://localhost/opencop-icons/HSWG/Trans_Airport_S2.png');
insert into icon (id, name, url) values (4523, 'Trans Airport S3',	'http://localhost/opencop-icons/HSWG/Trans_Airport_S3.png');
insert into icon (id, name, url) values (4524, 'Trans Airport S4',	'http://localhost/opencop-icons/HSWG/Trans_Airport_S4.png');
insert into icon (id, name, url) values (4525, 'Trans Air Traffic Control Facility S1',	'http://localhost/opencop-icons/HSWG/Trans_Air_Traffic_Control_Facility_S1.png');
insert into icon (id, name, url) values (4526, 'Trans Air Traffic Control Facility S2',	'http://localhost/opencop-icons/HSWG/Trans_Air_Traffic_Control_Facility_S2.png');
insert into icon (id, name, url) values (4527, 'Trans Air Traffic Control Facility S3',	'http://localhost/opencop-icons/HSWG/Trans_Air_Traffic_Control_Facility_S3.png');
insert into icon (id, name, url) values (4528, 'Trans Air Traffic Control Facility S4',	'http://localhost/opencop-icons/HSWG/Trans_Air_Traffic_Control_Facility_S4.png');
insert into icon (id, name, url) values (4529, 'Trans Bridge S1',	'http://localhost/opencop-icons/HSWG/Trans_Bridge_S1.png');
insert into icon (id, name, url) values (4530, 'Trans Bridge S2',	'http://localhost/opencop-icons/HSWG/Trans_Bridge_S2.png');
insert into icon (id, name, url) values (4531, 'Trans Bridge S3',	'http://localhost/opencop-icons/HSWG/Trans_Bridge_S3.png');
insert into icon (id, name, url) values (4532, 'Trans Bridge S4',	'http://localhost/opencop-icons/HSWG/Trans_Bridge_S4.png');
insert into icon (id, name, url) values (4533, 'Trans Bus Station S1',	'http://localhost/opencop-icons/HSWG/Trans_Bus_Station_S1.png');
insert into icon (id, name, url) values (4534, 'Trans Bus Station S2',	'http://localhost/opencop-icons/HSWG/Trans_Bus_Station_S2.png');
insert into icon (id, name, url) values (4535, 'Trans Bus Station S3',	'http://localhost/opencop-icons/HSWG/Trans_Bus_Station_S3.png');
insert into icon (id, name, url) values (4536, 'Trans Bus Station S4',	'http://localhost/opencop-icons/HSWG/Trans_Bus_Station_S4.png');
insert into icon (id, name, url) values (4537, 'Trans Ferry Terminal S1',	'http://localhost/opencop-icons/HSWG/Trans_Ferry_Terminal_S1.png');
insert into icon (id, name, url) values (4538, 'Trans Ferry Terminal S2',	'http://localhost/opencop-icons/HSWG/Trans_Ferry_Terminal_S2.png');
insert into icon (id, name, url) values (4539, 'Trans Ferry Terminal S3',	'http://localhost/opencop-icons/HSWG/Trans_Ferry_Terminal_S3.png');
insert into icon (id, name, url) values (4540, 'Trans Ferry Terminal S4',	'http://localhost/opencop-icons/HSWG/Trans_Ferry_Terminal_S4.png');
insert into icon (id, name, url) values (4541, 'Trans Helicopter Landing Site S1',	'http://localhost/opencop-icons/HSWG/Trans_Helicopter_Landing_Site_S1.png');
insert into icon (id, name, url) values (4542, 'Trans Helicopter Landing Site S2',	'http://localhost/opencop-icons/HSWG/Trans_Helicopter_Landing_Site_S2.png');
insert into icon (id, name, url) values (4543, 'Trans Helicopter Landing Site S3',	'http://localhost/opencop-icons/HSWG/Trans_Helicopter_Landing_Site_S3.png');
insert into icon (id, name, url) values (4544, 'Trans Helicopter Landing Site S4',	'http://localhost/opencop-icons/HSWG/Trans_Helicopter_Landing_Site_S4.png');
insert into icon (id, name, url) values (4545, 'Trans Lock S1',	'http://localhost/opencop-icons/HSWG/Trans_Lock_S1.png');
insert into icon (id, name, url) values (4546, 'Trans Lock S2',	'http://localhost/opencop-icons/HSWG/Trans_Lock_S2.png');
insert into icon (id, name, url) values (4547, 'Trans Lock S3',	'http://localhost/opencop-icons/HSWG/Trans_Lock_S3.png');
insert into icon (id, name, url) values (4548, 'Trans Lock S4',	'http://localhost/opencop-icons/HSWG/Trans_Lock_S4.png');
insert into icon (id, name, url) values (4549, 'Trans Maintenance Facility S1',	'http://localhost/opencop-icons/HSWG/Trans_Maintenance_Facility_S1.png');
insert into icon (id, name, url) values (4550, 'Trans Maintenance Facility S2',	'http://localhost/opencop-icons/HSWG/Trans_Maintenance_Facility_S2.png');
insert into icon (id, name, url) values (4551, 'Trans Maintenance Facility S3',	'http://localhost/opencop-icons/HSWG/Trans_Maintenance_Facility_S3.png');
insert into icon (id, name, url) values (4552, 'Trans Maintenance Facility S4',	'http://localhost/opencop-icons/HSWG/Trans_Maintenance_Facility_S4.png');
insert into icon (id, name, url) values (4553, 'Transport Air Accident',	'http://localhost/opencop-icons/HSWG/Transport_Air_Accident.png');
insert into icon (id, name, url) values (4554, 'Transport Air Hijacking',	'http://localhost/opencop-icons/HSWG/Transport_Air_Hijacking.png');
insert into icon (id, name, url) values (4555, 'Transport Air Theme',	'http://localhost/opencop-icons/HSWG/Transport_Air_Theme.png');
insert into icon (id, name, url) values (4556, 'Transportation Infrastructure Theme S1',	'http://localhost/opencop-icons/HSWG/Transportation_Infrastructure_Theme_S1.png');
insert into icon (id, name, url) values (4557, 'Transportation Infrastructure Theme S2',	'http://localhost/opencop-icons/HSWG/Transportation_Infrastructure_Theme_S2.png');
insert into icon (id, name, url) values (4558, 'Transportation Infrastructure Theme S3',	'http://localhost/opencop-icons/HSWG/Transportation_Infrastructure_Theme_S3.png');
insert into icon (id, name, url) values (4559, 'Transportation Infrastructure Theme S4',	'http://localhost/opencop-icons/HSWG/Transportation_Infrastructure_Theme_S4.png');
insert into icon (id, name, url) values (4560, 'Transport Marine Accident',	'http://localhost/opencop-icons/HSWG/Transport_Marine_Accident.png');
insert into icon (id, name, url) values (4561, 'Transport Marine Hijacking',	'http://localhost/opencop-icons/HSWG/Transport_Marine_Hijacking.png');
insert into icon (id, name, url) values (4562, 'Transport Marine Theme',	'http://localhost/opencop-icons/HSWG/Transport_Marine_Theme.png');
insert into icon (id, name, url) values (4563, 'Transport Rail Accident',	'http://localhost/opencop-icons/HSWG/Transport_Rail_Accident.png');
insert into icon (id, name, url) values (4564, 'Transport Rail Hijacking',	'http://localhost/opencop-icons/HSWG/Transport_Rail_Hijacking.png');
insert into icon (id, name, url) values (4565, 'Transport Rail Theme',	'http://localhost/opencop-icons/HSWG/Transport_Rail_Theme.png');
insert into icon (id, name, url) values (4566, 'Trans Port S1',	'http://localhost/opencop-icons/HSWG/Trans_Port_S1.png');
insert into icon (id, name, url) values (4567, 'Trans Port S2',	'http://localhost/opencop-icons/HSWG/Trans_Port_S2.png');
insert into icon (id, name, url) values (4568, 'Trans Port S3',	'http://localhost/opencop-icons/HSWG/Trans_Port_S3.png');
insert into icon (id, name, url) values (4569, 'Trans Port S4',	'http://localhost/opencop-icons/HSWG/Trans_Port_S4.png');
insert into icon (id, name, url) values (4570, 'Transport Vehicle Accident',	'http://localhost/opencop-icons/HSWG/Transport_Vehicle_Accident.png');
insert into icon (id, name, url) values (4571, 'Transport Vehicle Hijacking',	'http://localhost/opencop-icons/HSWG/Transport_Vehicle_Hijacking.png');
insert into icon (id, name, url) values (4572, 'Transport Vehicle Theme',	'http://localhost/opencop-icons/HSWG/Transport_Vehicle_Theme.png');
insert into icon (id, name, url) values (4573, 'Trans Rail Station S1',	'http://localhost/opencop-icons/HSWG/Trans_Rail_Station_S1.png');
insert into icon (id, name, url) values (4574, 'Trans Rail Station S2',	'http://localhost/opencop-icons/HSWG/Trans_Rail_Station_S2.png');
insert into icon (id, name, url) values (4575, 'Trans Rail Station S3',	'http://localhost/opencop-icons/HSWG/Trans_Rail_Station_S3.png');
insert into icon (id, name, url) values (4576, 'Trans Rail Station S4',	'http://localhost/opencop-icons/HSWG/Trans_Rail_Station_S4.png');
insert into icon (id, name, url) values (4577, 'Trans Rest Stop S1',	'http://localhost/opencop-icons/HSWG/Trans_Rest_Stop_S1.png');
insert into icon (id, name, url) values (4578, 'Trans Rest Stop S2',	'http://localhost/opencop-icons/HSWG/Trans_Rest_Stop_S2.png');
insert into icon (id, name, url) values (4579, 'Trans Rest Stop S3',	'http://localhost/opencop-icons/HSWG/Trans_Rest_Stop_S3.png');
insert into icon (id, name, url) values (4580, 'Trans Rest Stop S4',	'http://localhost/opencop-icons/HSWG/Trans_Rest_Stop_S4.png');
insert into icon (id, name, url) values (4581, 'Trans Ship Anchorage S1',	'http://localhost/opencop-icons/HSWG/Trans_Ship_Anchorage_S1.png');
insert into icon (id, name, url) values (4582, 'Trans Ship Anchorage S2',	'http://localhost/opencop-icons/HSWG/Trans_Ship_Anchorage_S2.png');
insert into icon (id, name, url) values (4583, 'Trans Ship Anchorage S3',	'http://localhost/opencop-icons/HSWG/Trans_Ship_Anchorage_S3.png');
insert into icon (id, name, url) values (4584, 'Trans Ship Anchorage S4',	'http://localhost/opencop-icons/HSWG/Trans_Ship_Anchorage_S4.png');
insert into icon (id, name, url) values (4585, 'Trans Toll Facility S1',	'http://localhost/opencop-icons/HSWG/Trans_Toll_Facility_S1.png');
insert into icon (id, name, url) values (4586, 'Trans Toll Facility S2',	'http://localhost/opencop-icons/HSWG/Trans_Toll_Facility_S2.png');
insert into icon (id, name, url) values (4587, 'Trans Toll Facility S3',	'http://localhost/opencop-icons/HSWG/Trans_Toll_Facility_S3.png');
insert into icon (id, name, url) values (4588, 'Trans Toll Facility S4',	'http://localhost/opencop-icons/HSWG/Trans_Toll_Facility_S4.png');
insert into icon (id, name, url) values (4589, 'Trans Traffic Control Point S1',	'http://localhost/opencop-icons/HSWG/Trans_Traffic_Control_Point_S1.png');
insert into icon (id, name, url) values (4590, 'Trans Traffic Control Point S2',	'http://localhost/opencop-icons/HSWG/Trans_Traffic_Control_Point_S2.png');
insert into icon (id, name, url) values (4591, 'Trans Traffic Control Point S3',	'http://localhost/opencop-icons/HSWG/Trans_Traffic_Control_Point_S3.png');
insert into icon (id, name, url) values (4592, 'Trans Traffic Control Point S4',	'http://localhost/opencop-icons/HSWG/Trans_Traffic_Control_Point_S4.png');
insert into icon (id, name, url) values (4593, 'Trans Traffic Inspection Facility S1',	'http://localhost/opencop-icons/HSWG/Trans_Traffic_Inspection_Facility_S1.png');
insert into icon (id, name, url) values (4594, 'Trans Traffic Inspection Facility S2',	'http://localhost/opencop-icons/HSWG/Trans_Traffic_Inspection_Facility_S2.png');
insert into icon (id, name, url) values (4595, 'Trans Traffic Inspection Facility S3',	'http://localhost/opencop-icons/HSWG/Trans_Traffic_Inspection_Facility_S3.png');
insert into icon (id, name, url) values (4596, 'Trans Traffic Inspection Facility S4',	'http://localhost/opencop-icons/HSWG/Trans_Traffic_Inspection_Facility_S4.png');
insert into icon (id, name, url) values (4597, 'Trans Tunnel S1',	'http://localhost/opencop-icons/HSWG/Trans_Tunnel_S1.png');
insert into icon (id, name, url) values (4598, 'Trans Tunnel S2',	'http://localhost/opencop-icons/HSWG/Trans_Tunnel_S2.png');
insert into icon (id, name, url) values (4599, 'Trans Tunnel S3',	'http://localhost/opencop-icons/HSWG/Trans_Tunnel_S3.png');
insert into icon (id, name, url) values (4600, 'Trans Tunnel S4',	'http://localhost/opencop-icons/HSWG/Trans_Tunnel_S4.png');
insert into icon (id, name, url) values (4601, 'Water Critical Valves S1',	'http://localhost/opencop-icons/HSWG/Water_Critical_Valves_S1.png');
insert into icon (id, name, url) values (4602, 'Water Critical Valves S2',	'http://localhost/opencop-icons/HSWG/Water_Critical_Valves_S2.png');
insert into icon (id, name, url) values (4603, 'Water Critical Valves S3',	'http://localhost/opencop-icons/HSWG/Water_Critical_Valves_S3.png');
insert into icon (id, name, url) values (4604, 'Water Critical Valves S4',	'http://localhost/opencop-icons/HSWG/Water_Critical_Valves_S4.png');
insert into icon (id, name, url) values (4605, 'Water Dam S1',	'http://localhost/opencop-icons/HSWG/Water_Dam_S1.png');
insert into icon (id, name, url) values (4606, 'Water Dam S2',	'http://localhost/opencop-icons/HSWG/Water_Dam_S2.png');
insert into icon (id, name, url) values (4607, 'Water Dam S3',	'http://localhost/opencop-icons/HSWG/Water_Dam_S3.png');
insert into icon (id, name, url) values (4608, 'Water Dam S4',	'http://localhost/opencop-icons/HSWG/Water_Dam_S4.png');
insert into icon (id, name, url) values (4609, 'Water Discharge Outfall S1',	'http://localhost/opencop-icons/HSWG/Water_Discharge_Outfall_S1.png');
insert into icon (id, name, url) values (4610, 'Water Discharge Outfall S2',	'http://localhost/opencop-icons/HSWG/Water_Discharge_Outfall_S2.png');
insert into icon (id, name, url) values (4611, 'Water Discharge Outfall S3',	'http://localhost/opencop-icons/HSWG/Water_Discharge_Outfall_S3.png');
insert into icon (id, name, url) values (4612, 'Water Discharge Outfall S4',	'http://localhost/opencop-icons/HSWG/Water_Discharge_Outfall_S4.png');
insert into icon (id, name, url) values (4613, 'Water Ground Water Well S1',	'http://localhost/opencop-icons/HSWG/Water_Ground_Water_Well_S1.png');
insert into icon (id, name, url) values (4614, 'Water Ground Water Well S2',	'http://localhost/opencop-icons/HSWG/Water_Ground_Water_Well_S2.png');
insert into icon (id, name, url) values (4615, 'Water Ground Water Well S3',	'http://localhost/opencop-icons/HSWG/Water_Ground_Water_Well_S3.png');
insert into icon (id, name, url) values (4616, 'Water Ground Water Well S4',	'http://localhost/opencop-icons/HSWG/Water_Ground_Water_Well_S4.png');
insert into icon (id, name, url) values (4617, 'Water Pumping Station S1',	'http://localhost/opencop-icons/HSWG/Water_Pumping_Station_S1.png');
insert into icon (id, name, url) values (4618, 'Water Pumping Station S2',	'http://localhost/opencop-icons/HSWG/Water_Pumping_Station_S2.png');
insert into icon (id, name, url) values (4619, 'Water Pumping Station S3',	'http://localhost/opencop-icons/HSWG/Water_Pumping_Station_S3.png');
insert into icon (id, name, url) values (4620, 'Water Pumping Station S4',	'http://localhost/opencop-icons/HSWG/Water_Pumping_Station_S4.png');
insert into icon (id, name, url) values (4621, 'Water Reservoir S1',	'http://localhost/opencop-icons/HSWG/Water_Reservoir_S1.png');
insert into icon (id, name, url) values (4622, 'Water Reservoir S2',	'http://localhost/opencop-icons/HSWG/Water_Reservoir_S2.png');
insert into icon (id, name, url) values (4623, 'Water Reservoir S3',	'http://localhost/opencop-icons/HSWG/Water_Reservoir_S3.png');
insert into icon (id, name, url) values (4624, 'Water Reservoir S4',	'http://localhost/opencop-icons/HSWG/Water_Reservoir_S4.png');
insert into icon (id, name, url) values (4625, 'Water Storage Tower S1',	'http://localhost/opencop-icons/HSWG/Water_Storage_Tower_S1.png');
insert into icon (id, name, url) values (4626, 'Water Storage Tower S2',	'http://localhost/opencop-icons/HSWG/Water_Storage_Tower_S2.png');
insert into icon (id, name, url) values (4627, 'Water Storage Tower S3',	'http://localhost/opencop-icons/HSWG/Water_Storage_Tower_S3.png');
insert into icon (id, name, url) values (4628, 'Water Storage Tower S4',	'http://localhost/opencop-icons/HSWG/Water_Storage_Tower_S4.png');
insert into icon (id, name, url) values (4629, 'Water Supply Infrastructure Theme S1',	'http://localhost/opencop-icons/HSWG/Water_Supply_Infrastructure_Theme_S1.png');
insert into icon (id, name, url) values (4630, 'Water Supply Infrastructure Theme S2',	'http://localhost/opencop-icons/HSWG/Water_Supply_Infrastructure_Theme_S2.png');
insert into icon (id, name, url) values (4631, 'Water Supply Infrastructure Theme S3',	'http://localhost/opencop-icons/HSWG/Water_Supply_Infrastructure_Theme_S3.png');
insert into icon (id, name, url) values (4632, 'Water Supply Infrastructure Theme S4',	'http://localhost/opencop-icons/HSWG/Water_Supply_Infrastructure_Theme_S4.png');
insert into icon (id, name, url) values (4633, 'Water Surface Water Intake S1',	'http://localhost/opencop-icons/HSWG/Water_Surface_Water_Intake_S1.png');
insert into icon (id, name, url) values (4634, 'Water Surface Water Intake S2',	'http://localhost/opencop-icons/HSWG/Water_Surface_Water_Intake_S2.png');
insert into icon (id, name, url) values (4635, 'Water Surface Water Intake S3',	'http://localhost/opencop-icons/HSWG/Water_Surface_Water_Intake_S3.png');
insert into icon (id, name, url) values (4636, 'Water Surface Water Intake S4',	'http://localhost/opencop-icons/HSWG/Water_Surface_Water_Intake_S4.png');
insert into icon (id, name, url) values (4637, 'Water Treatment Facility S1',	'http://localhost/opencop-icons/HSWG/Water_Treatment_Facility_S1.png');
insert into icon (id, name, url) values (4638, 'Water Treatment Facility S2',	'http://localhost/opencop-icons/HSWG/Water_Treatment_Facility_S2.png');
insert into icon (id, name, url) values (4639, 'Water Treatment Facility S3',	'http://localhost/opencop-icons/HSWG/Water_Treatment_Facility_S3.png');
insert into icon (id, name, url) values (4640, 'Water Treatment Facility S4',	'http://localhost/opencop-icons/HSWG/Water_Treatment_Facility_S4.png');
insert into icon (id, name, url) values (4641, 'xportcircle',	'http://localhost/opencop-icons/HSWG/xportcircle.png');
insert into icon (id, name, url) values (4642, 'xportdiamond',	'http://localhost/opencop-icons/HSWG/xportdiamond.png');
insert into icon (id, name, url) values (4643, 'xportrectangle',	'http://localhost/opencop-icons/HSWG/xportrectangle.png');
